### ISSUE TITLE
Clarification on SYSLOG_DEBUG

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#100]
https://github.com/lynxthecat/cake-autorate/blob/cd77880cfbbebad55863f8b95de01bffb92be53f/cake-autorate.sh#L65
```
[[ $type == "SYSLOG_DEBUG" ]] && (($use_logger)) && logger -t "cake-autorate" "$type: $log_timestamp $msg"
```

This is not what I intended here. My goal wad to have a simple way of also directing DEBUG messages into the system log. So these should stay type="DEBUG" and the first test is about whether the user configured this feature to be active:
```
(( ${log_DEBUG_messages_to_syslog} )) && [[ $type == "DEBUG" ]] && (($use_logger)) && logger -t "cake-autorate" "$type: $log_timestamp $msg"
```
with `log_DEBUG_messages_to_syslog` being exposed say in the config file....

**Comment by lynxthecat** [comment]
Yes I thought that might be a viable alternative. But you think better to have explicit variable? That'd be a lot of DEBUG messages on the syslog. But maybe worth it. Fancy coding up and pulling this too?

**Comment by moeller0** [comment]
This is really just a debugging help (in my case the system log is more convenient that autorate's own log, which is even larger with all its DATA and LOAD records, so large in fact that it is hard to capture a full night even though that seems required for the sleep debugging).

**Comment by moeller0** [comment]
I added a PR that seems to work as intended....

**Comment by lynxthecat** [comment]
Agreed. Closing now.
