### ISSUE TITLE
nit-picking in new log_msg

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#103]
https://github.com/lynxthecat/cake-autorate/blob/2f5c6de49d6b290edd0f17dacf6cb63449b7ba08/cake-autorate.sh#L56

I think you at least need to hoist
```
        [[ $type == "ERROR" ]] && (($use_logger)) && logger -t "cake-autorate" "$type: $log_timestamp $msg"
```
before that before the early exit; also does `continue` really work? I would expect a `return` to leave a function.

**Comment by lynxthecat** [comment]
Ah yes, fixing now.

**Comment by lynxthecat** [comment]
Ah, you mean this line:

(($log_DEBUG_messages_to_syslog)) && [[ $type == "DEBUG" ]] && (($use_logger)) && logger -t "cake-autorate" "

Shouldn't that be conditional on debug=1 or not? What do you think?

**Comment by moeller0** [comment]
No, I want the the ERROR reports still to hit the system log.... these are not DEBUG type messages that are optional.

making log_DEBUG_messages_to_syslog conditional on debug=1 is fine

**Comment by lynxthecat** [comment]
So this line won't touch type ERROR because it only returns on type DEBUG when debug=0...

**Comment by lynxthecat** [comment]
I've swapped the return for continue here: https://github.com/lynxthecat/cake-autorate/commit/6525f74923599a837626c17b1dc48661559cd4f7.

**Comment by moeller0** [comment]
Mmmh, you are right a message will only ever have one type. That said, I think we should go for a switch case statement here as that makes it very clear that type is mutually exclusive and if we use an early return for which type that is effective, no?

**Comment by moeller0** [comment]
With the case statement we would have something like:
```
case ${type} in
        DEBUG)
                [[ "${debug}" == 0 ]] && return 0        
                log_timestamp=${EPOCHREALTIME}
                ;;
        ERROR)
                log_timestamp=${EPOCHREALTIME}
                (($use_logger)) && logger -t "cake-autorate" "$type: $log_timestamp $msg"
                ;;
esac
```
that would reduce us to a single type test?

**Comment by lynxthecat** [comment]
Yes much better. I read up before a lot about case statements and they are much more efficient and a good way to speed up code. Fancy coding this one up too?

**Comment by moeller0** [comment]
I am happy to do that, but that will have to wait until Sunday evening/Monday, as I have no time right now for proper testing...

**Comment by lynxthecat** [comment]
Family comes first! Happy New Year 🎉🎉🎉!

**Comment by lynxthecat** [comment]
How about this: https://github.com/lynxthecat/cake-autorate/commit/a8441bc8406133ff474fc9f3c6562f7443f51f66.

**Comment by lynxthecat** [comment]
Maybe we can close now given this: https://github.com/lynxthecat/cake-autorate/commit/b2e7beb4c86a4fc93efa120074bf508baa8f6b4a?

**Comment by moeller0** [comment]
Looks good! Thanks!
