### ISSUE TITLE
Add this to all non-hot functions

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#111]
https://github.com/lynxthecat/cake-autorate/blob/b2b2ec1a6c238719df2daf3281046084e0f3853a/cake-autorate.sh#L1039

For debugging it would be helpful if we would add this stanza to all functions. Now, some functions like concurrent_read_integer() might be too hot to always cause additional log messages (both from a run-time cost and from a log size perspective) but all functions called sparsely enough should report this if DEBUG output is requested, no?

**Comment by lynxthecat** [comment]
Agreed. Doing this now.

**Comment by lynxthecat** [comment]
OK - here we are: https://github.com/lynxthecat/cake-autorate/commit/754673676b10e58b5e1d350ced67b40e7aa8f7fc. 

Have I caught everything?

**Comment by moeller0** [comment]
Not sure, still too brain-foggy to do code review, but I started a test run with the latest code and I see a lot of the messages, so you certainly caught a lot, probably all worth instrumenting...

**Comment by lynxthecat** [comment]
Closing for now since I think I got it all. Thanks for the suggestion.
