### ISSUE TITLE
How to choose upload/download interfaces?

### ISSUE THREAD

**Issue by Quba1** [lynxthecat/cake-autorate#114]
First thing first, I want to thank you all contributors for a great job. This script is incredible and turned my crap internet into quite usable connection.

I have a question regarding selection of upload/download interfaces `ul_if` and `dl_if`. I have selected those interfaces mostly by intuition and I presume I guessed correctly as the script seems to work.

Firstly, I'm wondering why there are two separate interfaces for download and upload? Doesn't `wan` both uploads and downloads data? Why then `wan` is used only for upload?

Secondly, for the choosing download interface, how can `tc qdisc ls` be used? I have no experience with that command so I don't really know what its output means. For the `dl_if` I have chosen a `br-lan` device that bridges two physical ports in my router with four vlan interfaces. All traffic seems to go through both `wan` and `br-lan` and the script seems to work. But I would like to know how to make that choice of interfaces not as a guess-work.

Once again, thanks for a great work! I ask those questions even though script for me works, so that future less-experienced users will have an easier job of setting options correctly.

PS
I think there is a typo in the README as there is: 

> `dl_if` | Interface that uploads data (check `tc qdisc ls`)

and I think it should be:

> `dl_if` | Interface that **downloads** data (check `tc qdisc ls`)

**Comment by lynxthecat** [comment]
I am pleased that you like the script. So cake-autorate is designed to adjust the bandwidth set for existing cake interfaces. Thus the interfaces need to be set to the same interfaces on which cake is applied. Cake is always applied on different interfaces for download and upload (you can verify which cake interfaces are active just by running 'tc qdisc ls') and how cake is setup is set up for a given configuration is not something that cake-autorate tries to guess. So the interfaces must be set correctly for cake-autorate to run properly. Typically the interfaces will be something like 'wan' for upload and 'ifb4wan' for download, but this hinges on the mechanism used to set up the cake interfaces in the first place. Hope this is helpful?

**Comment by Quba1** [comment]
Yes, that it indeed very helpful. I now know what to look for in the `tc qdisc ls`, and I was able to set cake-autorate properly and now my bufferbloat results are even better. Thanks for your help.

**Comment by lynxthecat** [comment]
Excellent. Let me please encourage you to I troeuce yourself and post on the cake-autorate thread on the OpenWrt forum.

https://forum.openwrt.org/t/cake-w-adaptive-bandwidth/135379

We can help you tweak your config for further optimisation. And new data is always appreciated.
