### ISSUE TITLE
re-decorate variables again?

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#116]
https://github.com/lynxthecat/cake-autorate/blob/ff1d7df64929c99b2e85a4d8fb8eb3b4d1d89b35/cake-autorate.sh#L456
```
			alpha=$(( (( rtt_us >= rtt_baselines_us[${reflector}] )) ? alpha_baseline_increase : alpha_baseline_decrease ))
```

I am not really comfortable with this reduced notation and would very much prefer to decorate all variables (unless on the left of an assignment) with ${} so that it is unambiguously clear what is a variable and what is not. These decorations might not be strictly necessary, but for a casual shell reader/writer like myself this helps a lot.

**Comment by lynxthecat** [comment]
Recently I thought I'd try to make how variables are decorated consistent throughout all the code and as part of that I did adopt your preferred use of curly brackets everywhere outside the arithmetic expansion context. In the arithmetic expansion context it seems that any name reference gets followed until a number is found. So even if you do something funky like x=5; z=x then ((z)) gets evaluated to 5. How cool is that? And don't you think when you know that dollar and brackets within arithmetic expansion context is not needed it becomes neater without all of that cluttering up the equations?

**Comment by gameinn1** [comment]
Hi moeller0

This isn't related at all but I didn't know how else to get in touch with you. Are you the person who wrote the info about the Sky config at sqm details page on openwrt? "For my ISP (Sky UK) things are straightforward" stuff. If so I would like to discuss the wan packet overhead for other UK ISP.

**Comment by moeller0** [comment]
> And don't you think when you know that dollar and brackets within arithmetic expansion context is not needed it becomes neater without all of that cluttering up the equations?

For me this muddies the water a bit. Say with your reference trick you notice the return variable by lack of decoration in the caller, so I really like the decoration as clear indicator of "value of variable" versus "name/reference of variable". Sure this makes things longer but also simpler to parse. Shell is still a bit foreign to me, especially bash ;)

**Comment by moeller0** [comment]
> Hi moeller0
> 
> This isn't related at all but I didn't know how else to get in touch with you. Are you the person who wrote the info about the Sky config at sqm details page on openwrt? "For my ISP (Sky UK) things are straightforward" stuff. If so I would like to discuss the wan packet overhead for other UK ISP.

I am neither in the UK nor a Sky customer, so I did not write that; I am happy to discus overhead, but would propose you open a new thread over in the OpenWrt forum (if you add a @moeller0 to the text I get a notice), as this seems to be only tangentially related to autorate or decoration of variables, no?

**Comment by lynxthecat** [comment]
Hey @moeller0 look at that you are famous though! I remember seeking get in touch with you based in all your input about overhead on OpenWrt back when I experimented with an Asus router running Asus Merlin.

**Comment by moeller0** [comment]
Hrm, not 100% sure that this is what I want to be remembered for ;) artifacts of 20th century technology...
I only stumbled into this tar-pit due to having an ADSL-link and still wanting determistic low-latency traffic shaping, which required to dig out the existing references (it is not that I "invented" the whole topic, I am standing on the shoulders of giants here...) and actually keep it from being forgotten (and re-discovered) over-and-over again inside the bufferbloat/OpenWrt community. All the heavy lifting had been done by others, I essentially just collected bits and pieces distributed over the internet.

**Comment by moeller0** [comment]
Coming back to the topic, I asked and you convinced me that we will stick to no-decorations for "arithmetic expansion context" so let me close this issue.
