### ISSUE TITLE
ping_extra_args should be a string not args

### ISSUE THREAD

**Issue by rany2** [lynxthecat/cake-autorate#117]
Config makes it seem like this should be a bash array, but cake-autorate only takes the first argument of ping_extra_args (it does `$ping_extra_args` instead of `${ping_extra_args[@]}`.

We might want to either:
- fix the example config
- fix cake-autorate.sh

Thanks for this!

**Comment by lynxthecat** [comment]
So right now we have:

```
# extra arguments for ping or fping
# e.g., here is how you can set the correct outgoing interface and
# the firewall mark for ping:
# ping_extra_args="-I wwan0 -m $((0x300))"
# Unfortunately, fping does not offer a command line switch to set
# the firewall mark.
# WARNING: no error checking so use at own risk!
ping_extra_args=""
```

Am I missing something? Is this in 'main' or in 'testing'?

**Comment by rany2** [comment]
https://github.com/lynxthecat/cake-autorate/blob/4195bd78ff545b25ab3120b3eb68f6ffb7ebbe52/cake-autorate_config.sh#L99-L102

**Comment by rany2** [comment]
All references to $ping_extra_args treat it as a string not a bash array. Example: https://github.com/lynxthecat/cake-autorate/blob/main/cake-autorate.sh#LL500C37-L504C24. This is in main.

**Comment by lynxthecat** [comment]
Ah, seems like this has been fixed in 'testing'. We are about to push 'testing' to main. Please can you test 'testing' and report with findings about whether this aspect and any other aspect works?

**Comment by rany2** [comment]
Sure, I wasn't aware there was a testing branch. I falsely assumed that the main branch is where all the development is going on.

**Comment by lynxthecat** [comment]
Would REALLY value your feedback on 'testing' since about to release cake-autorate 1.2.0 based on it. It has a ton of improvements (see the CHANGELOG there).

**Comment by rany2** [comment]
I'll let you know if I have any further comments, but so far it seems to working great! Thank you for this work!
