### ISSUE TITLE
[testing branch] cake-autorate sometimes doesn't restart properly

### ISSUE THREAD

**Issue by rany2** [lynxthecat/cake-autorate#120]
It doesn't happen all the time but sometimes it just doesn't restart and gets stuck. Only solution is to pkill -9 it and remove the /var/run/cake-autorate/primary directory and then start again.

```
root@gw:~# ps aux|grep cake
root      3944  0.0  0.0      0     0 ?        Z    18:00   0:00 [cake-autorate.s] <defunct>
root      3946 14.6  0.0   3288  2356 ?        S    18:00   1:06 /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
root      3947  0.0  0.0      0     0 ?        Z    18:00   0:00 [cake-autorate.s] <defunct>
root      4158  0.0  0.0   2152  1672 ?        S    17:00   0:00 /bin/bash /root/cake-autorate/cake-autorate_launcher.sh
root      4212 15.0  0.0   3176  2748 ?        S    17:00  10:06 /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
root      4244  0.0  0.0   2744  1328 ?        S    17:00   0:00 /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
root      4274  4.1  0.0   3080  2108 ?        S    17:00   2:45 /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
root      6147  3.1  0.0   3112  2148 ?        S    17:00   2:05 /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
root      6149  0.8  0.0   3252  2288 ?        S    17:00   0:32 /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
root     11052  0.0  0.0   1144   820 pts/0    S+   18:07   0:00 grep cake
```

**Comment by lynxthecat** [comment]
Yes that's a known issue that developed very recently (see cake-autorate
thread on OpenWrt forum). I've not had enough time to figure it out yet.

**Comment by lynxthecat** [comment]
Really appreciate your efforts here. I think the latest attempt needs some further thinking given my comments on the commits though. Namely we can't always just delete the run directory given multiple instances and we shouldn't necessarily immediate kill maintain pingers because a pid of pinger or monitor might be about to get written to. In the latter case I addressed this by setting variable and checking in while loop to ensure we cleanly exit after any rotation.

**Comment by rany2** [comment]
yay!

**Comment by lynxthecat** [comment]
Huge congratulations on getting us this far in such a short time. Now let's see if it withstands testing from others too!
