### ISSUE TITLE
startup syslog message order

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#124]
https://github.com/lynxthecat/cake-autorate/blob/2ec8b3a4a33a8957528c63385c9c1c2502cf4196/cake-autorate.sh#L1319

I wonder whether the rotate_logfile() call should not come after the SYSLOG start message. Currently we get:
```
root@turris:~# logread | grep autorate
Feb  8 07:52:16 turris cake-autorate.vdsl2: DEBUG: 1675842736.684407 Starting: rotate_log_file with PID: 17972
Feb  8 07:52:16 turris cake-autorate.vdsl2: DEBUG: 1675842736.690461 Starting: print_headers with PID: 17972
Feb  8 07:52:16 turris cake-autorate.vdsl2: INFO: 1675842736.694487 Starting cake-autorate with PID: 17972 and config: /root/cake-autorate/cake-autorate_config.vdsl2.sh
```
and I think that the INFO should ideally be the first message for a normal autorate start (if we error out earlier having earlier ERROR is fine as we need instanceID and config path for a meaningful message decoration and there can be problems on the way of determining those, but the in normal operating mode it would be nice if the INFO messages would nicely bracket all messages).
Now this is a bit cosmetic, since DEBUG records are not really intended for the SYSLOG, but maybe worth considering?

**Comment by lynxthecat** [comment]
Indeed I really appreciate your thoughts on this because I wasn't sure what to do. But I thought if we rotate the log file after the syslog then the start message in the log file will get wiped out. But maybe that's fine? I may have messed this up by moving the rotate log file higher up in the main routine specifically because I expected the syslog start message to be the first line in the log file. 

What do you think about the above?

**Comment by moeller0** [comment]
> But I thought if we rotate the log file after the syslog start message then the start message in the log file will get wiped out. But maybe that's fine?

Good point, this might be a case were perfect is impossible... I was looking at this from the syslog/console output perspective and did not think about the main log. Given that on the console it does not matter much (who is going to look at that besides you and me anyway) and in the normal case DEBUG messages do not make it into the syslog. So I guess this is already a decent compromise you found that aims to keep log and syslog somewhat aligned.

**Comment by rany2** [comment]
If this is just about aesthetics we could have that call to `rotate_log_file` not print any debug information.

**Comment by moeller0** [comment]
For debugging these records are useful, so let's not silence them any further ;) and DEBUG records are only logged at explicit request, so the issue is cosmetic but will not affect normal users by default. So I am fine with keeping it as is, I commented because I had not understood the consequence for our normal logfile...
