### ISSUE TITLE
Which octave package to install on openwrt?

### ISSUE THREAD

**Issue by xman0980** [lynxthecat/cake-autorate#126]
I cannot figure out what octave package to install on openwrt.

opkg install octave gives an error, so apparently its not built in. I even tried through the gui, and there is no reference to octave.

Thanks!

**Comment by rany2** [comment]
You cannot run Octave on your router, you'll need to copy that file (with something like scp) to your computer and run that Octave script on your computer that way

**Comment by xman0980** [comment]
Ahhh okay. Thanks alot for the quick response. Much appreciated.
