### ISSUE TITLE
Proc man issue

### ISSUE THREAD

**Issue by lynxthecat** [lynxthecat/cake-autorate#155]
@rany2 today on issuing 'service cake-autorate stop' I encountered:

```
root@OpenWrt:~/cake-autorate# ps |grep -e bash -e fping -e sleep
 4515 root      1252 R    grep -e bash -e fping -e sleep
25599 root      3100 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
25659 root      3368 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh

root@OpenWrt:~/cake-autorate# strace -y -p 25599
strace: Process 25599 attached
read(0<pipe:[1652178]>, ^Cstrace: Process 25599 detached
 <detached ...>

root@OpenWrt:~/cake-autorate# strace -y -p 25659
strace: Process 25659 attached
writev(1<pipe:[1652172]>, [{iov_base="1676480971.647490 8.8.4.4 174052"..., iov_len=76}, {iov_base="\n", iov_len=1}], 2^Cstrace: Process 25659 detached
 <detached ...>
```

```
LOAD; 2023-02-15-17:11:05; 1676481065.074141; 1676481065.073785; 0; 0; 20000; 20000
LOAD; 2023-02-15-17:11:05; 1676481065.276464; 1676481065.276123; 0; 10; 20000; 20000
DEBUG; 2023-02-15-17:11:05; 1676481065.283838; Starting: cleanup_and_killall with PID: 25576
INFO; 2023-02-15-17:11:05; 1676481065.284792; Stopping cake-autorate with PID: 25576 and config: /root/cake-autorate/cake-autorate_config.primary.sh
INFO; 2023-02-15-17:11:05; 1676481065.285571; Killing all background processes and cleaning up temporary files.
DEBUG; 2023-02-15-17:11:05; 1676481065.347087; Starting: kill_maintain_pingers with PID: 25640
DEBUG; 2023-02-15-17:11:05; 1676481065.455135; Terminating maintain_pingers.
LOAD; 2023-02-15-17:11:05; 1676481065.479333; 1676481065.478991; 6; 0; 20000; 20000
DEBUG; 2023-02-15-17:11:05; 1676481065.527439; Killing fping instance.
DEBUG; 2023-02-15-17:11:05; 1676481065.607128; Starting: kill_pinger with PID: 25640
LOAD; 2023-02-15-17:11:05; 1676481065.682327; 1676481065.681970; 0; 0; 20000; 20000
LOAD; 2023-02-15-17:11:05; 1676481065.885106; 1676481065.884762; 0; 0; 20000; 20000
LOAD; 2023-02-15-17:11:06; 1676481066.088189; 1676481066.087831; 0; 0; 20000; 20000
LOAD; 2023-02-15-17:11:06; 1676481066.291272; 1676481066.290869; 0; 0; 20000; 20000
DEBUG; 2023-02-15-17:11:06; 1676481066.605228; Starting: kill_maintain_log_file with PID: 25610
DEBUG; 2023-02-15-17:11:06; 1676481066.606485; Starting: flush_log_fd with PID: 25610
```

```
Wed Feb 15 17:11:06 2023 user.notice cake-autorate.unknown: ERROR: 1676481066.340923 /root/cake-autorate/cake-autorate_lib.sh: line 113: printf: write error: Broken pipe
Wed Feb 15 17:11:06 2023 user.notice cake-autorate.unknown: ERROR: 1676481066.430795 /root/cake-autorate/cake-autorate_lib.sh: line 21: 25640 Killed                  "${@}"
Wed Feb 15 17:11:06 2023 user.notice cake-autorate.primary: INFO: 1676481066.743153 Stopped cake-autorate with PID: 25576 and config: /root/cake-autorate/cake-autorate_config.primary.sh
```

Looks like the printf failed for some reason in the code below:

```
_proc_man_get_key_value()
{
        local key=${1}

        lock "${PROC_STATE_FILE_LOCK:?}"
        trap 'unlock "${PROC_STATE_FILE_LOCK:?}"' RETURN

        while read -r line; do
                if [[ ${line} =~ ^${key}= ]]; then
                        printf '%s\n' "${line#*=}"
                        return 0
                fi
        done < "${PROC_STATE_FILE:?}"
        return 1
}
```

**Comment by rany2** [comment]
What's the issue?

**Comment by rany2** [comment]
I don't think it's proc-man related. Try reverting this part: https://github.com/lynxthecat/cake-autorate/pull/152/files#diff-ca337b46dad0145d671f0f133f086fd8cee99c296ee83ec4d3fd24682f4c855bL560

**Comment by lynxthecat** [comment]
The one in monitor on line 468 which was designed to deal with the possibility of the read blocking? 

```
	while true
	do
		while read -r -t 1 timestamp reflector _ seq_rtt 2>/dev/null
```

**Comment by rany2** [comment]
It does kill by fire, in fact you could see it killing fping with SIGKILL in the log file. 

> line 21: 25640 Killed

I believe what prevents it from killing is that the main process ended up exiting and closing stdout in the process.

**Comment by lynxthecat** [comment]
Hmm, so how come the proc man lost track of:

```
25599 root      3100 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
25659 root      3368 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
```

**Comment by rany2** [comment]
I don't think these are managed by proc-man, but I might be wrong.

**Comment by rany2** [comment]
Anyway it's worth a try to restore the while true trick, maybe it was legitimately needed. I just didn't appreciate it because it isn't efficient

**Comment by lynxthecat** [comment]
I think the idea was that all processes are managed by proc man. 

https://github.com/lynxthecat/cake-autorate/blob/64e039d8fa90580ef06101540d0fa9cb56ccaa3b/cake-autorate.sh#L699

Is the issue the kill by fire in a higher level process triggering too quickly then?

**Comment by rany2** [comment]
I don't think so, one second timeout is enough and in the worst case it wouldn't impact the parent process.

**Comment by lynxthecat** [comment]
OK, but what then explains those processes not getting killed by the proc man? I am trying to figure out what went wrong here, and my thought process was that perhaps the killing of a parent process somehow prevented the killing of the children.

**Comment by rany2** [comment]
Could you make sure that these processes are actually being managed by proc man? All you have to do to make sure that this is the case is to remove the lines that remove the run path and then check the last state of `/var/run/cake-autorate/primary/proc_state`.

**Comment by lynxthecat** [comment]
No processes are backgrounded from cake-autorate.sh:

https://github.com/lynxthecat/cake-autorate/blob/master/cake-autorate.sh

this can be verified by searching for ! in cake-autorate.sh and observing that there are no backgrounded processes as before in which PID stored using pid=${!}. 

Thus necessarily the proc man is managing all backgrounded processes.

**Comment by rany2** [comment]
Could you still just comment out the removing run path part from the cleanup function? It will be useful to know which process isn't being killed properly. Proc man will designate a successfully killed process as having a PID of -1 in the proc state file.

**Comment by lynxthecat** [comment]
```
root@OpenWrt:/tmp/run/cake-autorate/primary# cat proc_state
maintain_log_file=8123
monitor_achieved_rates=8143
maintain_pingers=8153
pinger_0=8163
monitor_0=8172
root@OpenWrt:/tmp/run/cake-autorate/primary# ps |grep -e fping -e bash -e slee
 8087 root      2356 S    {cake-autorate_l} /bin/bash /root/cake-autorate/cake-autorate_launcher.sh
 8089 root      3196 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-au
 8108 root      3052 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-au
 8123 root      3108 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-au
 8143 root      3168 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-au
 8153 root      3324 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-au
 8163 root      1928 S    fping --timestamp --loop --period 300 --interval 50 --timeout 10000 1.1.1.1 1.0.0.1 8.8.8.8
 8172 root      3328 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-au
 8369 root      3288 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-au
 8374 root      3132 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-au
```

I presume 8089 is the main process. 

Do the remaining processes relate to the proc man? So actually perhaps the processes above that were left alive were the proc man itself?

**Comment by rany2** [comment]
The remaining processes CANNOT relate to proc man. proc man is not a daemon of sorts, it only runs when issued and it won't run in a subshell, so basically the shell won't be forked.

**Comment by lynxthecat** [comment]
Any idea what the remaining process relate to? I presume these are the ones that locked out in the previous bad exit.

**Comment by rany2** [comment]
My best guess is that it relates to sleep_s but seeing your strace I'm not totally convinced it is the case.

**Comment by lynxthecat** [comment]
Ah right, yes. So there are transient sleep_s processes, but those shouldn't matter. 

Admittedly this happened when I cake-autorate.sh during live run to add the printf variant. Would you expect that to affect things or not relevant?

**Comment by rany2** [comment]
Yes I expect that to affect things but only if you edited the files while cake-autorate was in operation.

**Comment by lynxthecat** [comment]
Yes I think I did actually. So this could be a false alarm.

**Comment by rany2** [comment]
We could modify cake-autorate so that it won't be vulnerable to these false alarms if you like

**Comment by rany2** [comment]
So I guess this could be closed for now?

**Comment by lynxthecat** [comment]
Yes probably - but just before I do what do you mean:

"We could modify cake-autorate so that it won't be vulnerable to these false alarms if you like"

**Comment by rany2** [comment]
Basically modifying cake-autorate so that the entire script is read, closed and only then executed.

**Comment by rany2** [comment]
> would that be to run from a cloned .sh file?

not what I was thinking, I was thinking of just exporting all the functions into the BASH_FUNC_* environ and then exec-ing a "main function"...

**Comment by rany2** [comment]
admittedly it will make debugging a living hell, so on second thought ignore my proposal.

**Comment by lynxthecat** [comment]
Understood. I'll close this for now and re-open if I see it again. Editing whilst running and expecting all to be fine is just a bit dumb on my part I suppose.
