### ISSUE TITLE
How to update the script?

### ISSUE THREAD

**Issue by Quba1** [lynxthecat/cake-autorate#156]
I have v1.1.0 installed on my device, but I would like to update to `master` version to use `cake-autorate` with `mwan3`.

Do I just need to run install script again or do I need to replace files manually as described in release notes?

**Comment by rany2** [comment]
No, it's sufficient to rerun the install script. However make sure that you use the most recent one.

**Comment by lynxthecat** [comment]
And please let us know you get on!

**Comment by Quba1** [comment]
Thanks for the responses. The package updated just fine. 

One thing that users need to be aware of when updating to latest version is that script has to be configured again. That's because config files structure changed and configuration is not preserved. But `cake-autorate_config.sh` file is not removed during update so configuration can just be copied.
