### ISSUE TITLE
cake-autorate config position for overrides

### ISSUE THREAD

**Issue by lynxthecat** [lynxthecat/cake-autorate#159]
What do you think gents, shall we add a line like:

```
# add custom overrides here
```

right before this line here:

https://github.com/lynxthecat/cake-autorate/blob/172c765c80b410929a0e81bcde3e7aa0ec759677/cake-autorate_config.primary.sh#L25

**Comment by rany2** [comment]
Oppose, too cryptic. This is better IMO:

```
# See cake-autorate_defaults.sh for additional configuration options
# that can be set in this config to override the defaults
```

**Comment by rany2** [comment]
This could be closed now
