### ISSUE TITLE
Incorporate pizzazz in project description

### ISSUE THREAD

**Issue by dtaht** [lynxthecat/cake-autorate#162]
You would do better if the description of the project was less vague.

"Sets CAKE bandwidth in dependence upon traffic load and latency"

Alternatives might include:

"Rips the excessive latency and jitter out of your crappy 3,4,5G and Starlink networks."

**Comment by lynxthecat** [comment]
The present description is admittedly somewhat functional and lacks pizzazz.

**Comment by AT-StephenDetomasi** [comment]
More pizzazz would be quite a welcome addition. The description would even be funky, with the right sort of implementation.

**Comment by lynxthecat** [comment]
@rany2 or @moeller0 any suggestions for more pizzazz? 

This description:

"Sets CAKE bandwidth in dependence upon traffic load and latency"

is for me nice and functionally descriptive, but it for sure lacks pizzazz. 

This alternative:

"Rips the excessive latency and jitter out of your crappy 3,4,5G and Starlink networks."

has more pizzazz but it lacks the functional description and insults the connection of its users. 

Any ideas?

**Comment by dtaht** [comment]
s/your// ? pizazze++

**Comment by lynxthecat** [comment]
How about:

> Terminator of excess latency and jitter programmed for use with CAKE on variable rate connections.

**Comment by rany2** [comment]
> How about:
> 
> > Terminator of excess latency and jitter programmed for use with CAKE on variable rate connections.

This sounds more like legalese than a marketing pitch.

**Comment by lynxthecat** [comment]
Well I think pizzazz or funk ought not to entirely displace function.

**Comment by lynxthecat** [comment]
> Masters worlds inhabited by excess latency and jitter.

**Comment by lynxthecat** [comment]
I've switched over to the above. Any thoughts before I close this?

**Comment by rany2** [comment]
A bit over the top but looks fine!

**Comment by lynxthecat** [comment]
I'm open minded. Incorporating a healthy degree of pizzazz and optionally funk is actually quite a challenge.

**Comment by lynxthecat** [comment]
@rany2 which do you prefer:

**Neutralises the excess latency and jitter terrorizing variable rate connections!**

or

**Neutralise the excess latency and jitter terrorizing your variable rate connection!**

Or something else?

**Comment by rany2** [comment]
@lynxthecat First one sounds nicer

**Comment by moeller0** [comment]
So I am a big fan of under-promise, but over-deliver, and hence would phrase this a tad less boisterous. But then the whole goal here is marketing so my approach is not going to help...

**Comment by lynxthecat** [comment]
Indeed my original description was: 

**Sets CAKE bandwidth in dependence upon traffic load and latency**

But that's patent-language-esque, whereas as pointed out by @dtaht, a little 'razzle dazzle' is in order.

**Comment by moeller0** [comment]
Sets CAKE bandwidth in dependence upon traffic load and latency:
...thereby making your link punch above its weight class
... making your variable rate link sing and dance
... keeping latency low and responsiveness high and the internet snappy.

I know, I know too little pizza ;)

**Comment by lynxthecat** [comment]
Hehe, yeah we need way more razzle dazzle. 

**Eviscerates excess latency and jitter thereby to electrify your variable rate connection!**

**Comment by rany2** [comment]
This is why none of us are marketers :laughing:

**Comment by stephendt** [comment]
Okay, here's my serious suggestion:

"Cake Autorate supercharges your router's ability to handle congestion and slowdowns from ISPs, allowing for low latency and stable operation, no matter the time of day".

**Comment by dtaht** [comment]
Thank you all for cracking me up multiple times. Please pass the doobie. Feel free to try out multiple phrases over time. A typical marketing strategy is to do just that - keep trying things until they hit.

**Comment by dtaht** [comment]
Mentioning LTE, 5G and starlink in the project description, high up, is a SEO trick.

**Comment by lynxthecat** [comment]
> Mentioning LTE, 5G and starlink in the project description, high up, is a SEO trick.

I didn't thank of that!

**Comment by dtaht** [comment]
Also changing it every so often weaks the google search algo so it lands there.

Another place for a kvetch somewhere in the text:

While *ideally* fq_codel or CAKE would already be running natively on LTE, 5G, and [especially Starlink](https://www.youtube.com/watch?v=c9gLo6Xrwgw&t=6s), they presently don´t despite these latency-fighting algorithms being available for a very long time. While cake-autorate can help enormously - our hope is, by demonstration, that those technologies not already running cAKE natively will do so, and the need for this script fade into history.

**Comment by lynxthecat** [comment]
> While cake-autorate can help enormously - our hope is, by demonstration, that those technologies not already running CAKE natively will do so, and the need for this script fade into history.

What odds would you put on this being achieved in the next decade?

**Comment by dtaht** [comment]
I'd actually give it pretty good odds!
