### ISSUE TITLE
No shebang needed

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#173]
https://github.com/lynxthecat/cake-autorate/blob/948003e3dbebd7276933452790f36697466bcda7/cake-autorate_lib.sh#L1

For files that are not supposed to be executed directly, but only sourced by other scripts, no shebang `#!/bin/bash` is required or arguable desirable.

**Comment by rany2** [comment]
I agree but it is to keep it for linters that need to know which shell version to target. This is why I left it as is.

**Comment by moeller0** [comment]
Here is my take on shellcheck and linters in general, if they require contortions that make the code worse, one is better of judiciously ignoring them or just transiently adding this line before running the tool.
I grant you that this is less of an issue than the gratuitous encapsulation of things into otherwise useless functions (that ended up introducing new bugs), but this is IMHO the wrong mindset.

**Comment by rany2** [comment]
Well I could use a shell check directive inside the file (special comment at the start) to specify the dialect but I felt keeping the shebang was more elegant.

**Comment by moeller0** [comment]
Well, I guess you created that file so your prerogative.

**Comment by lynxthecat** [comment]
@rany2 what would the directive be? I looked here:

https://www.shellcheck.net/wiki/Directive

but I can't see what would need to be written in place of  #!/bin/bash?
