### ISSUE TITLE
How to remove?

### ISSUE THREAD

**Issue by ItsThaKingHomie** [lynxthecat/cake-autorate#182]
I'm a newbie on OpenWRT and tried to install this package but couldn't manage as I want.  I want to remove installed files to free up space but don't know how to do it.   Also  when I ls  the  main directory after ssh login,  there is only  cake-autorate  file.  

I'm using Windows Powershell.  Thanks.

**Comment by rany2** [comment]
and `rm /etc/rc.d/*cake-autorate`

**Comment by ItsThaKingHomie** [comment]
Thanks for helping.  Now I understand more, I could do that with ftp connection via Cyberduck.
