### ISSUE TITLE
wait4 hang in maintain_pingers()

### ISSUE THREAD

**Issue by lynxthecat** [lynxthecat/cake-autorate#183]
@rany2 I am trying to investigate a hang on wait4 in the maintain_pingers() process. 

```
maintain_pingers = 31593

root@OpenWrt-1:~# strace -y -p 31593
strace: Process 31593 attached
wait4(-1,
```

I am working on the code in the 'lynxthecat-patch-1' branch.

https://github.com/lynxthecat/cake-autorate/blob/b14c7d0607cf7cd53962bb0a8c73c8164b0bd496/cake-autorate.sh#L1137

I can't figure out which line is causing this hang. 

I wondered about: 

https://github.com/lynxthecat/cake-autorate/blob/b14c7d0607cf7cd53962bb0a8c73c8164b0bd496/cake-autorate_lib.sh#L29

But I don't think that could cause it. 

Else is this the right order in terms of killing processes, then closing fd:

https://github.com/lynxthecat/cake-autorate/blob/b14c7d0607cf7cd53962bb0a8c73c8164b0bd496/cake-autorate.sh#L552

Any ideas?

**Comment by rany2** [comment]
Can you try:

```

sleep_s()
{
	# Calling the external sleep binary could be rather slow,
	# especially as it is called very frequently and typically on mediocre hardware.
	#
	# bash's loadable sleep module is not typically available
	# in OpenWRT and most embedded systems, and use of the bash
	# read command with a timeout offers performance that is
	# at least on a par with bash's sleep module.
	#
	# For benchmarks, check the following links:
	# - https://github.com/lynxthecat/cake-autorate/issues/174#issuecomment-1460057382
	# - https://github.com/lynxthecat/cake-autorate/issues/174#issuecomment-1460074498

	local sleep_duration_s=${1} # (seconds, e.g. 0.5, 1 or 1.5)
	( read -r -t "${sleep_duration_s}" -u "${__sleep_fd}" || : ) &
	wait "${!}"
}

**Comment by rany2** [comment]
Actually why the fuck are we forking it?

**Comment by lynxthecat** [comment]
Thanks. Seems like an improvement. But is there a scenario you can think of with the previous formulation that would result in a hang on a wait4(-1 ... call? The -1 means wait for any child. Even if the forking was unecessary, I can't figure out what's causing the hang. 

Does the order of killing and closing the file descriptor seem correct to you?

**Comment by rany2** [comment]
@lynxthecat I think only way to test these variants.

**Comment by rany2** [comment]
> Is there a scenario you can think of with the previous formulation that would result in a hang on a wait4(-1 ... call? The -1 means wait for any child. Even if the forking was unecessary, I can't figure out what's causing the hang.

I'm not really sure why bash calls -1 even though we obviously only tried to wait for a specific PID. My best guess is that the cause is that a subshell was not created which would have forced bash to use a specific PID, but even then I'm not too sure about that.

Kind of wish OpenWRT's busybox built with usleep by default... kind of stupid situation if you ask me.

**Comment by lynxthecat** [comment]
@rany2 my gut is that the sleep isn't the cause of the hang (albeit I will change it because it seems like it's more efficient). 

I think it's maybe to do with the way I am sending data between FIFOs:

- tsping sends data to parse_preprocessor_fd [here
](https://github.com/lynxthecat/cake-autorate/blob/b14c7d0607cf7cd53962bb0a8c73c8164b0bd496/cake-autorate.sh#L544)
- parse_preprocessor reads from parse_preprocessor_fd [here](https://github.com/lynxthecat/cake-autorate/blob/b14c7d0607cf7cd53962bb0a8c73c8164b0bd496/cake-autorate.sh#L494) via process substitution [here](https://github.com/lynxthecat/cake-autorate/blob/b14c7d0607cf7cd53962bb0a8c73c8164b0bd496/cake-autorate.sh#L541)
- parse_preprocessor prepends REFLECTOR_RESPONSE and sends data to parse_tsping_fd
- parse_tsping reads data from parse_tsping_fd [here](https://github.com/lynxthecat/cake-autorate/blob/b14c7d0607cf7cd53962bb0a8c73c8164b0bd496/cake-autorate.sh#L530)
- parse_tsping sends processed data to main_fd [here](https://github.com/lynxthecat/cake-autorate/blob/b14c7d0607cf7cd53962bb0a8c73c8164b0bd496/cake-autorate.sh#L646)

**Comment by rany2** [comment]
Doesn't `terminate` call sleep_s behind the scenes?

**Comment by lynxthecat** [comment]
Actually so far so good - no hang with: https://github.com/lynxthecat/cake-autorate/commit/0261add44b7a3d73e9f2459ca51530a20981a1f5. Trying not to get my hopes up too much though in case it turns out to be something else. 

In any case, thank you very much for your input here @rany2 - at the very least this will reduce CPU consumption.

**Comment by lynxthecat** [comment]
And still no hang. So marking this as closed for now. Thanks again @rany2.
