### ISSUE TITLE
Error: can't open '/var/run/cake-autorate/*/proc_state

### ISSUE THREAD

**Issue by richb-hanover** [lynxthecat/cake-autorate#187]
I never tested anything in the ANALYSIS.md file, so I figured I would try it. I got the following error:

```bash
root@router:~#    kill -USR1 $(cat /var/run/cake-autorate/*/proc_state | grep -E    '^maintain_log_file=' | cut -d= -f2)
cat: can't open '/var/run/cake-autorate/*/proc_state': No such file or directory
ash: you need to specify whom to kill
```

It looks to me as if the underlying directory structure in `/var/run/cake-autorate` has changed. Could someone take a look at how to fix the instructions? Thanks.

**Comment by lynxthecat** [comment]
Thanks @richb-hanover. Fixed in https://github.com/lynxthecat/cake-autorate/commit/c3dfefb0b2b21aedfb6106bee260603c60c28bf7.

**Comment by richb-hanover** [comment]
Hmmm... Gave the same error message.

I had to put change `maintain_log_file=` to `maintain_log_file =` (additional space)
```
   awk -F= '/^maintain_log_file =/ {print $2}' /var/run/cake-autorate/*/proc_pids | xargs kill -USR1
```

**Comment by richb-hanover** [comment]
I expanded the regex to handle an optional space and it works fine.

`awk -F= '/^maintain_log_file[ ]*=/ {print $2}' ...`

I will respond separately to your email. Thanks.
