### ISSUE TITLE
For easier/more testing...

### ISSUE THREAD

**Issue by richb-hanover** [lynxthecat/cake-autorate#19]
CAKE-autorate.sh seems good enough for people to test. A couple thoughts for making it easier for people to try it:

- Merge the CAKE-autorate branch into main. It's time :-)
- Include a version number and describe the process for finding it for bug reports
- Change the name of `defaults.sh` to `config.sh` (Oh - you just did!)
- Consider adding a script that retrieves all the useful stats and configurations for troubleshooting similar to [this one](https://github.com/sqm-autorate/sqm-autorate/blob/develop/main/lib/getstats.sh) 
- You could then provide a [straightforward command for retrieving that info](https://github.com/sqm-autorate/sqm-autorate/discussions/108) via SSH from another computer.
- Provide a simple installation procedure. I'm using the one below.

```bash
#! /bin/bash
# Basic installation script for CAKE-autorate.sh
# See https://github.com/lynxthecat/sqm-autorate for details

# Retrieve required packages
opkg update
opkg install bash iputils-ping coreutils-sleep

# Set up CAKE-autorate files

# cd to the /root directory
cd /root/

# create the CAKE-autorate directory if it's not present
[ -d CAKE-autorate ] || mkdir CAKE-autorate

# cd into it
cd CAKE-autorate/
rm *

SRC_DIR="https://raw.githubusercontent.com/lynxthecat/CAKE-autorate/main/"
wget $SRC_DIR"CAKE-autorate.sh"
wget $SRC_DIR"config.sh"

chmod +x *.sh

echo " "
echo "Now edit the config.sh file" 
echo " "
echo "Then start the software with 'bash ./CAKE-autorate.sh'"

```

**Comment by lynxthecat** [comment]
Thanks. Yes I was planning to put this into main. Would you have tips for doing so? My 'main' branch has generated a lot of interest I believe from what GitHub tells me, so I need to be careful to keep that in tact. 

Could I simply rename 'CAKE-autorate' to 'main', or should I merge? 

How can I keep 'main' and the others in tact?

@moeller0 any thoughts in this respect?

**Comment by moeller0** [comment]
I am no expert on these matters, but as long as you keep branches (so not delete them) moving stuff from one branch to the next should be acceptable, just make a notice on the front page about delegating current "main" to "historic_main" (or what ever you call it) and moving CAKE-autorate to the front/main.



> ```shell
> # Retrieve required packages
> opkg update 
> opkg install bash
> ```

Here I would use something like:
# Retrieve required packages
# Uncomment the next two lines to update the opkg pakage list and install bash
# make sure you have enough space available
 #opkg update 
# pkg install bash

for the simple reason that this has side-effects that can cause issues on routers tight on storage/memory so users should consciously perform that operation, no?

**Comment by richb-hanover** [comment]
@moeller0 - good points. 

But `bash` seems to be required (I couldn't just use `sh ./CAKE-autorate.sh` - I don't know why).

Perhaps an investigation into the reason for [these error messages](https://github.com/lynxthecat/sqm-autorate/issues/16#issuecomment-1059635423) when using `sh ...` could remove the requirement to install `bash` entirely... (I know there are a few differences between the  busybox `ash` and the standard `bash` shell...)

**Comment by lynxthecat** [comment]
Bash was an intentional design choice. Ash is just too limited - no arrays, no integer maths, etc. My script in 'main' at the moment is ash + awk, but it is horrible to read and work with.

**Comment by richb-hanover** [comment]
OK. Totally fine. But that makes installing `bash` a requirement.

**Comment by lynxthecat** [comment]
I have renamed the repository and branches. Let me know if you see any issues with that. 

When I get time I will rework the readme for the new bash implementation in 'main'

**Comment by richb-hanover** [comment]
Excellent! To expand the second bullet point in the original note

* Include a version number ...
* How to discover/display the (new) version number? It could be as simple as `grep _VERSION CAKE-autorate.sh`
* Create a CHANGELOG.md that documents the changes to the repo. I think they're most effective when they have the form:

   > #### Version - Date
   > Optional sentence or two describing the intent of this change
   > * first change
   > * second change
   > * ... etc...

Thanks!

**Comment by moeller0** [comment]
For the changelog, I think if you name you commits reasonably just looking at the commit link would do, currently however the commit titles seem not expressive enough for that.

**Comment by richb-hanover** [comment]
I updated the script in the original post to install the current (as of 20 Mar 2022) CAKE-autorate.sh. The steps in the README do not actually install the files into /root/CAKE-autorate/...

**Comment by lynxthecat** [comment]
Thanks @richb-hanover. I fixed the readme. Do you know whether it is necessary to 'chmod +x ./config.sh'?

**Comment by richb-hanover** [comment]
1. I don't know if `chmod +x ./config.sh` is necessary. I haven't taken the time to do the research.
2. I like the `[ -d CAKE-autorate ] || mkdir CAKE-autorate` because then copy-pastes always work, or it can become a script.

Thanks!
