### ISSUE TITLE
hping3 still listed as an option in defaults

### ISSUE THREAD

**Issue by eode** [lynxthecat/cake-autorate#193]
This is a trivial matter, but `tsping` isn't listed as an option in defaults, and `hping3` is listed -- yet there isn't any supporting code for `hping3`, and there is supporting code for `tsping`.

**Comment by lynxthecat** [comment]
Yes I see. Thanks for raising. I'll fix when I get back from my trip to Munich.

**Comment by lynxthecat** [comment]
Fixed here: https://github.com/lynxthecat/cake-autorate/commit/f0aa62dd5fd8e91093b252072d825d33f537b303.
