### ISSUE TITLE
Create version identifier file on install

### ISSUE THREAD

**Issue by lynxthecat** [lynxthecat/cake-autorate#196]
@rany2 can you see a way to have your installer script create a version file `cake-autorate_version` with the lines:

```
version = 2.0.0
commit = df5e679
```

@rany2, @moeller0 and @richb-hanover as a related question, our current structure for /root/cake-autorate/ is:

```
root@OpenWrt-1:~/cake-autorate# ls -alh
drwxr-xr-x    2 root     root         664 Jun 23 19:01 .
drwxr-xr-x    1 root     root         856 Jun 25 16:17 ..
-rwxr-xr-x    1 root     root       76.0K Jun 20 12:49 cake-autorate.sh
-rw-rw-r--    1 root     root        1.9K Jun 20 13:27 cake-autorate_config.primary.sh
-rw-rw-r--    1 root     root       11.0K Jun 18 10:20 cake-autorate_defaults.sh
-rwxrwxr-x    1 root     root         574 May  5 13:34 cake-autorate_launcher.sh
-rw-rw-r--    1 root     root        2.9K Jun  6 13:35 cake-autorate_lib.sh
-rwxrwxr-x    1 root     root        3.2K Mar 30 21:55 cake-autorate_setup.sh
```

Should we consider renaming to:

```
cake-autorate.sh
config.primary.sh
defaults.sh
lib.sh
setup.sh
```

**Comment by richb-hanover** [comment]
re: renaming files in /root/cake-autorate: I don't feel strongly either way. It does decrease typing for people doing configuration, but requires a careful check of the documentation to make sure it stays correct.

**Comment by rany2** [comment]
> @rany2 can you see a way to have your installer script create a version file `cake-autorate_version` with the lines:
> 
> ```
> version = 2.0.0
> commit = df5e679
> ```

That should be easy, I have a rough idea on how to work on that.

**Comment by lynxthecat** [comment]
Any thoughts on the filenames?

**Comment by rany2** [comment]
I am all for it as well, I find the current structure ugly. Though we should really be careful about not messing up docs like @richb-hanover said

**Comment by lynxthecat** [comment]
OK I'll work on that.

**Comment by rany2** [comment]
This could be closed now

**Comment by lynxthecat** [comment]
Yes, kudos @rany2 for implementing these changes.
