### ISSUE TITLE
Config file validation

### ISSUE THREAD

**Issue by rany2** [lynxthecat/cake-autorate#207]
Some kind of validation of the config file provided by the user would be great, in that if a config is found to contain some invalid assignment, the script will abort giving the user the chance to figure out what changed in the new version and update their config properly.

**Comment by rany2** [comment]
If you want you could hold off the release until this is done, but it's your call.

**Comment by lynxthecat** [comment]
I'll hold off. I've held off for so long, what's a few more improvements.
