### ISSUE TITLE
Set "default" branch to v3.0 in Github?

### ISSUE THREAD

**Issue by richb-hanover** [lynxthecat/cake-autorate#239]
Currently, the URL https://github.com/lynxthecat/cake-autorate gets to the `master` branch. 

Is that the preferred destination? Would it be better to go to the `v3.0` branch? Thanks.

**Comment by rany2** [comment]
I think it would be better to keep the default branch as the development branch. This is so that when a user contributes to cake-autorate, the default branch that they would want to merge against would be `master` not `v3.0` which is meant to be as unchanging as possible.

**Comment by richb-hanover** [comment]
That's fine by me. I would be tempted to change the third paragraph of the README to say something like:

> ## Status
> 
> This is the **Development** (`master`) branch. New work on cake-autorate appears here. It is not guaranteed to be stable.
>
> The **Stable Version** for production/every day use is 3.0.1 available from the `v3.0 branch` at https://github.com/lynxthecat/cake-autorate/tree/v3.0

(Feel free to reword, but it's my sense that the important points are: master === branch for development; inclusion of a link to the stable branch.)

**Comment by rany2** [comment]
Would renaming `master` to `unstable` work fine as well?

**Comment by richb-hanover** [comment]
You have to consider what the branch names (and defaults) tell your audience. 

cake-autorate is no longer highly experimental. And it is definitely "ready for prime time" - that is, for the set of people who have heard, "This is really cool", and are motivated to work through the hassles of configuring text files in nano or vi.

My advice remains to set the default branch to v3.0 - random people who arrive at the site will get the version "we want them to try out". Intrepid people who want to try the latest dev version can dig out the "master" or "development" branch. (I prefer "development" to "unstable".) Thanks for listening

**Comment by rany2** [comment]
@lynxthecat I think he makes a good point, many users are probably not familiar with git or GitHub either. However I think it might be worthwhile to add a disclaimer in the README to make sure users know to send pull requests against master not v3.0

**Comment by lynxthecat** [comment]
I favour just adding the disclaimer that @richb-hanover suggested with excellent wordsmithing as usual. @richb-hanover I wonder if you could issue a pull request for the same?
