### ISSUE TITLE
Have a maint script that automatically creates the "Status" text

### ISSUE THREAD

**Issue by rany2** [lynxthecat/cake-autorate#244]

**Comment by lynxthecat** [comment]
The "Status" text?

**Comment by rany2** [comment]
https://github.com/lynxthecat/cake-autorate#status

**Comment by lynxthecat** [comment]
How about this? My sed skills admittedly leave a little to be desired.

**Comment by lynxthecat** [comment]
Does this work:

https://github.com/lynxthecat/cake-autorate/blob/eebf9abe3f706e97e24830fe083f00d8739ce12b/maint/update_setupsh_branch.sh#L19

Is the idea to checkout new branch v3.1, then run:

```
 ./maint/update_setupsh_branch.sh "v3.2"
```

because the sed for me doesn't seem to work.w 

But perhaps I'm missing something.
