### ISSUE TITLE
tsping mode is not compatible with mwan3

### ISSUE THREAD

**Issue by patrakov** [lynxthecat/cake-autorate#246]
Some time ago, the code was changed to pass `--machine-readable=' '` argument to tsping. Unfortunately, the `mwan3 use lte exec` wrapper (prefix command) mangles this. It is a bug in `mwan3`, but bugs there are never fixed. So please try to avoid triggering it. In other words, please try to avoid the need for any special characters that need quoting or otherwise cannot pass through the `$*` construct, such as spaces. Maybe use $IFS that includes the comma when parsing.

**Comment by patrakov** [comment]
I have a workaround: instead of `ping_prefix_string="mwan3 use lte exec"`, I can use `ping_extra_args="-f 768"`.

**Comment by lynxthecat** [comment]
Do you think we should change the code to accommodate this? If so, I wonder if you could issue a pull request?

**Comment by rany2** [comment]
I have an idea for a fix, just give me a few moments.

**Comment by lynxthecat** [comment]
@rany2 are you still intending to try to fix this?

**Comment by rany2** [comment]
@lynxthecat yes, just too busy with other things and forgot about this.
