### ISSUE TITLE
Version 3.1 release

### ISSUE THREAD

**Issue by lynxthecat** [lynxthecat/cake-autorate#252]
@rany2 any chance you could help with releasing 3.1? There are a few significant changes now and I just pushed a fix to resolve a start-up crash when logging to file is disabled - see the [changelog](https://github.com/lynxthecat/cake-autorate/blob/master/CHANGELOG.md).

**Comment by rany2** [comment]
I sure can.

**Comment by rany2** [comment]
Done

**Comment by lynxthecat** [comment]
Excellent, thanks!

**Comment by lynxthecat** [comment]
I forgot to add the Starlink config: 

https://forum.openwrt.org/t/cake-w-adaptive-bandwidth/135379/3262

What's the best way to handle this?

**Comment by rany2** [comment]
@lynxthecat Just update it on master like usual and I'll backport it to 3.1 as a patch release

**Comment by lynxthecat** [comment]
Many thanks - here is the commit: https://github.com/lynxthecat/cake-autorate/commit/3c0e013f17327e8877151d8ee9ccaead0cf847ca.
