### ISSUE TITLE
Make ATM adjustment more obvious

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/CAKE-autorate#26]
https://github.com/lynxthecat/CAKE-autorate/blob/ff783c97c0765a7af7f5cd785897e33a18c9e24f/CAKE-autorate.sh#L212

I would propose to change
`max_wire_packet_size_bits=$(( 424*(($max_wire_packet_size_bits+376)/384) `
to
`max_wire_packet_size_bits=$(( *53*8)*(($max_wire_packet_size_bits+(47*8))/(48*8)) '
M/AAL5 quantisation will understand what this is doing.

**Comment by lynxthecat** [comment]
Hmm, what if I just add a comment explaining? Redoing the calculations every time seems unnecessary?

**Comment by moeller0** [comment]
At what rate will you be calling this, that three integer multiplication will make a noticeable difference?

**Comment by lynxthecat** [comment]
Ah, it's just on initialization.

**Comment by moeller0** [comment]
In which case even 300 multiplications would be acceptable, no?

**Comment by lynxthecat** [comment]
OK how about this:

```
get_max_wire_packet_size_bits()
{
        local interface=$1
        local -n max_wire_packet_size_bits=$2

        read -r max_wire_packet_size_bits < "/sys/class/net/${interface}/mtu"
        [[ $(tc qdisc show dev $interface) =~ (atm|noatm)[[:space:]]overhead[[:space:]]([0-9]+) ]]
        [[ ! -z "${BASH_REMATCH[2]}" ]] && max_wire_packet_size_bits=$((8*($max_wire_packet_size_bits+${BASH_REMATCH[2]})))
        # atm compensation = 53*ceil(X/48) bytes = 8*53*((X+8*(48-1)/(8*48)) bits = 424*((X+376)/384) bits
        [[ "${BASH_REMATCH[1]}" == "atm" ]] && max_wire_packet_size_bits=$(( 424*(($max_wire_packet_size_bits+376)/384) ))
}

```

 I think we need comments anyway to explain this! 

Reminds me when I saw the Quake3 arena code and a 'wtf' comment next to:

https://en.wikipedia.org/wiki/Fast_inverse_square_root#Overview_of_the_code

**Comment by moeller0** [comment]
Your choice, IMHO the clearest would be to do all calculations as max_wire_packet_size_bytes and add a final conversion line:
```
max_wire_packet_size_bits=$(( max_wire_packet_size_biytes * 8 ))
```

**Comment by lynxthecat** [comment]
But is it correct?

**Comment by lynxthecat** [comment]
Have you seen how I now use this to modify the monitor_achieved_rates interval:

```
 # read in the max_wire_packet_rtt_us
{
    flock -s 200
    read -r max_wire_packet_rtt_us < "/tmp/CAKE-autorate/max_wire_packet_rtt_us"
 } 200>/tmp/CAKE-autorate/max_wire_packet_rtt_us_lock
                                                                                                                                                                             compensated_monitor_achieved_rates_interval_us=$(( (($base_monitor_achieved_rates_interval_us>(10*$max_wire_packet_rtt_us) )) ? $base_monitor                t_end_us=${EPOCHREALTIME/./}  
```

**Comment by moeller0** [comment]
```
root@turris:~# cat /sys/class/net/pppoe-wan/mtu
1492
root@turris:~# interface=pppoe-wan
root@turris:~# [[ $(tc qdisc show dev $interface) =~ (atm|noatm)[[:space:]]overhead[[:space:]]([0-9]+) ]] && echo ${BASH_REMATCH[2]}
34
```
and
```
root@turris:~# read -r max_wire_packet_size_bits < "/sys/class/net/${interface}/mtu"
root@turris:~# echo $max_wire_packet_size_bits
1492
root@turris:~# [[ $(tc qdisc show dev $interface) =~ (atm|noatm)[[:space:]]overhead[[:space:]]([0-9]+) ]]
root@turris:~# [[ ! -z "${BASH_REMATCH[2]}" ]] && max_wire_packet_size_bits=$((8*($max_wire_packet_size_bits+${BASH_REMATCH[2]})))
root@turris:~# echo $max_wire_packet_size_bits
12208
root@turris:~#  [[ "${BASH_REMATCH[1]}" == "atm" ]] && max_wire_packet_size_bits=$(( 424*(($max_wire_packet_size_bits+376)/384) ))
root@turris:~# echo $max_wire_packet_size_bits
12208
```

so no this does seem to work:
`qdisc cake 80a9: dev pppoe-wan root refcnt 2 bandwidth 36Mbit diffserv3 dual-srchost nat nowash no-ack-filter split-gso rtt 100.0ms noatm overhead 34 mpu 88 `

But does it do the right thing if atm is set?
```
root@turris:~# echo $max_wire_packet_size_bits
1492
root@turris:~# [[ $(tc qdisc show dev $interface) =~ (atm|noatm)[[:space:]]overhead[[:space:]]([0-9]+) ]]
root@turris:~# [[ ! -z "${BASH_REMATCH[2]}" ]] && max_wire_packet_size_bits=$((8*($max_wire_packet_size_bits+${BASH_REMATCH[2]})))
root@turris:~# echo $max_wire_packet_size_bits
12208
root@turris:~#  [[ "${BASH_REMATCH[1]}" == "noatm" ]] && max_wire_packet_size_bits=$(( 424*(($max_wire_packet_size_bits+376)/384) ))
root@turris:~# echo $max_wire_packet_size_bits
13568
```
13568/8 = 1696
ceil((1492+ 34)/48) * 53 = 32 * 53 = 1696

So yes, works as expected, but see my other issue about how this is actually returned to the caller?

**Comment by moeller0** [comment]
`base_delay_thr_ms` not sure that is the best naming here, when reading this I rather thing about the the adjusted part for the worst case packet size. After all that is the value users are supoosed to use.

Other than that, it might make sense to implement a toggle for the individual auto-adjustement variables to help isolate for debugging?



> I'm anxious to ensure I got all this right - it took me some time to figure out how to implement it last night. I think this may be fairly important because my LTE connection is exceptional. Many LTE connections give more like 0-10Mbit/s, not 10-80Mbit/s like mine.

Not clear to me that on << 1 Mbps links the code really is going to help much, @petrakov is an experienced user with appropriate adjusted expectations (all he wants is to avoid >= 2 second bloat spikes) and for the range from 12 to 1.3 Mbps the MTU delay only increases from 1ms to 10ms which is nice to auto-adjust for, but not really necessary, from 1.2 to 0.12 Mbps however we go to ~100ms MTU delay and that needs special handling...

But I applaud your aiming at actually creating useful code even for extreme situations instead of taking short cuts.

**Comment by lynxthecat** [comment]
I'm confused about the above aspect you indicate not working. Would you be able to echo:

 echo "${BASH_REMATCH[1]}"

**Comment by moeller0** [comment]
> I'm confused about the above aspect you indicate not working.

Sorry, that should have read working as designed. On my link with noatm, the adjustment should not trigger, but I initially had not considered that, this is why I tested more and edited the post from "no it dos not work" to "yes it does work", and added the test with `[[ "${BASH_REMATCH[1]}" == "noatm" ]]`

**Comment by lynxthecat** [comment]
Ah, so it's OK? Phew! I'll rename the base variable - any suggestion?

**Comment by lynxthecat** [comment]
Just keep as 'delay_thr_ms' and use compensated in addition?

**Comment by moeller0** [comment]
> any suggestion?
I like your naming proposal above.

**Comment by lynxthecat** [comment]
BTW I'd really appreciate your input on the ping handling aspect, I'm lost with that at the moment.

**Comment by moeller0** [comment]
What exactly about the ping handling are you concerned about?

**Comment by lynxthecat** [comment]
https://github.com/lynxthecat/CAKE-autorate/issues/24

**Comment by moeller0** [comment]
One of the was the synchronization after a PAUSE/RESTART cycle? Wasn't the idea to simply kill the background process and restart again with the same out-spacing logic as the intiial staggered start-up?

**Comment by lynxthecat** [comment]
Yes I've implemented that. But I'm really not sure how to handle timeout of ping responses. iputils-ping doesn't support timeout but it does have -O flag which means that if a reply has not been received at the time of the next send it spits out this:

```
root@OpenWrt:~# ping -i 0.1 -O -D 1.2.3.4
PING 1.2.3.4 (1.2.3.4) 56(84) bytes of data.
[1650021833.486369] no answer yet for icmp_seq=1
[1650021833.596339] no answer yet for icmp_seq=2
[1650021833.706762] no answer yet for icmp_seq=3
[1650021833.816735] no answer yet for icmp_seq=4
[1650021833.926880] no answer yet for icmp_seq=5
[1650021834.036746] no answer yet for icmp_seq=6
[1650021834.146914] no answer yet for icmp_seq=7
```

**Comment by moeller0** [comment]
> Perhaps fixed 500ms delay processing timeout is fine to clear the fifo on processor saturation(?), but I'm not sure how to handle situation where 10s - 30s delayed pings come in.

You implement an additional timer process that puts something into the FIFO every say 500ms which will wake up the main loop which will see this wakeup, and check wether the last received RTT value was later than 500ms if yes, it appears delays are too high and counter measures can be initiated (what ever these be). Would that work?
Just make sure to add a new field to the record type you use over the FIFO, say TYPE with either SAMPLE or TIMER or similar so the main loop can distinguish between the two?

**Comment by lynxthecat** [comment]
That seems like a good idea. Do you think it's OK to accept and process ping results that are like 30s old and include in bufferbloat delays count at time of receipt?

**Comment by moeller0** [comment]
> Do you think it's OK to accept and process ping results that are like 30s old and include in bufferbloat delays count at time of receipt?

Probably not, if all reflectors return such hogwash, that safest seems to go to the minimum rates and stay there until better delay data becomes available. For individual samples (if only some reflectors are affected), I probably would ignore samples >> 5 seconds or so (this should never trigger for real data except for extreme situations like airplane WiFi that buffers data for seconds when no base station is available, but there autorate will not work, well).



> iputils-ping doesn't support timeout in the way I thought it did, but it does have -O flag, which means that if a reply has not been received at the time of the next send it spits out this:

Yes, that is where a single shot approach is easier to deal with... but at a steep CPU cost.

**Comment by moeller0** [comment]
> BTW did you figure out what was preventing this running on your system?

No, but I did not look yesterday evening... will probably try with the new code... I did try to run from shell and not as service, because I want more control over this and be able to stop experiments at all times.

**Comment by moeller0** [comment]
> > BTW did you figure out what was preventing this running on your system?
> 
> No, but I did not look yesterday evening... will probably try with the new code... I did try to run from shell and not as service, because I want more control over this and be able to stop experiments at all times.

I am tight in expectiong that when called from the command line I should expect log output in the terminal I started this from?

**Comment by lynxthecat** [comment]
Yes - it should start printing lines pretty quickly.

**Comment by moeller0** [comment]
> Do you have a fairly recent version of bash?
```
root@turris:~# bash --version
GNU bash, version 5.0.17(1)-release (arm-openwrt-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

> I can't think why it might jam. It does rely on /tmp use if that could be related?

`/tmp/` is writable and I see the CAKE-autorate directory appear, including the lock files.



> The fifo is kept open by the exec 3<> call. Could you try adding 'set -x' to see where it is sticking?

Maybe tonight, the network is in use right now, so no time for experiments, until later.

**Comment by moeller0** [comment]
Mmmh, seems my ping binary is odd, instead od the expected icmp_seq it returns icmp_req
```
+ read -r timestamp reflector seq rtt_baseline_us rtt_us rtt_delta_us
+ [[ icmp_req=13 ttl=60 time=9.43 ms =~ icmp_req=([0-9]+).*time=([0-9]+)\.?([0-9]+)?[[:space:]]ms ]]
```
adjusting the pattern match from
[[ icmp_seq=13 ttl=60 time=9.43 ms =~ icmp_req=([0-9]+).*time=([0-9]+)\.?([0-9]+)?[[:space:]]ms ]] 
to 
[[ icmp_req=13 ttl=60 time=9.43 ms =~ icmp_req=([0-9]+).*time=([0-9]+)\.?([0-9]+)?[[:space:]]ms ]]
get things working...

This might be caused by Turris OS 5 being based on OpenWrt 19 and hence using a rather oldish iputils-ping

Please test the following on your machine:

```
[[ $seq_rtt =~ icmp_[s|r]eq=([0-9]+).*time=([0-9]+)\.?([0-9]+)?[[:space:]]ms ]] || continue   
```

this hopefully matches against both icmp_seq and icmp_req, it works for me, but I can only test with my old ping....

**Comment by moeller0** [comment]
Other than that it seems to work well, it takes ~10 seconds to ramp up from a base of 12Mbps to my maximum of 105 and considerably longer to go back to the base rates after the load subsided.

**Comment by lynxthecat** [comment]
Wow, that looks great. Which settings did you change I wonder?

I tested and your change works fine at my end and so I will merge this commit. Thanks for discovering this and proposing the solution.

**Comment by moeller0** [comment]
I just set the 6 rates and the delay threshold, after taking care of the ping output difference the script just worked out of the box, pretty impressive. I think it shows and pays off that you are constantly refining and improving the code.
This has come a long way since autumn/winter! Thanks to your tenacity and willingness to iteratively try and test different potential approaches.

**Comment by lynxthecat** [comment]
And thanks to all your input. Seems to be working really well now for a number of different use cases like LTE and Starlink. How's CPU usage at your end? I can get this down by ditching the flock calls because apparently the only issue is reading in blank file so I can just just read and if blank use old values or reread rather than bother with the flock since those calls are expensive.
