### ISSUE TITLE
How to install it on AsusWRT-Merlin?

### ISSUE THREAD

**Issue by pitris90** [lynxthecat/cake-autorate#267]
When I try to install this script on asuswrt-merlin, nothing happens (config isnt created, but even no error message is displayed)
```shell
pitris90@RT-AX86U_Pro:/tmp/home/root# sh /tmp/cake-autorate_setup.sh
pitris90@RT-AX86U_Pro:/tmp/home/root#
```

I also tried this script: [https://github.com/LiveWire1968/Asus-cake-autorate](https://github.com/LiveWire1968/Asus-cake-autorate) but there was some error:
```shell
pitris90@RT-AX86U_Pro:/tmp# sh /tmp/cake-autorate_setup.sh
/tmp/cake-autorate_setup.sh: line 70: syntax error: unexpected end of file (expecting "fi")
```

**Comment by lynxthecat** [comment]
cake-autorate has been written for use on OpenWrt, albeit porting to Asus Merlin should be straightforward. 

If you look at the install script @LiveWire1968 wrote, it uses an older version of cake-autorate and some of the filenames have changed. You could try just copying the correct files - see:

https://github.com/lynxthecat/cake-autorate

You need 'cake-autorate.sh', 'config.primary.sh', 'defaults.sh', 'lib.sh'.

**Comment by pitris90** [comment]
Hmm, I will try that, but I think I will need some help.

**Comment by lynxthecat** [comment]
Try asking here:

https://www.snbforums.com/forums/asuswrt-merlin.42/

**Comment by LiveWire1968** [comment]
I dont use it anymore, but I updated the files on github. Just drop all 4 in /jffs/scripts make sure the entware packages are installed
[https://github.com/LiveWire1968/Asus-cake-autorate/tree/main](url)

**Comment by LiveWire1968** [comment]
@lynxthecat for future reference. Im pretty sure the only changes needed this go around was changing #/bin/bash to #/opt/bin/bash in the scripts, then changing cake-autorate.sh to look for scripts in /jffs/scripts.  I think i missed one part of log files should go into /tmp, not /var/log on asus

**Comment by lynxthecat** [comment]
Thanks for your input here @LiveWire1968.

**Comment by rany2** [comment]
@LiveWire1968 does asuswrt have a /usr/bin/env ?

**Comment by LiveWire1968** [comment]
> @LiveWire1968 does asuswrt have a /usr/bin/env ?

yes
