### ISSUE TITLE
TSping

### ISSUE THREAD

**Issue by LiveWire1968** [lynxthecat/cake-autorate#268]
@lynxthecat  did you compile tsping for openwrt? I was messing with it, but meson and ninja seem to be a issue on the asus.

**Comment by lynxthecat** [comment]
I’d create an issue here: 

https://github.com/Lochnair/tsping

**Comment by LiveWire1968** [comment]
> I’d recommend creating an issue against tsping itself here:
> 
> https://github.com/Lochnair/tsping

I got it to compile. it will ping localhost on the router, but says "sent 100 packets, received none" when i try anything outside the local net :/

**Comment by lynxthecat** [comment]
Are you sending to hosts that support icmp 13?

**Comment by LiveWire1968** [comment]
> Are you sending to hosts that support ICMP type 13? I think at least 9.9.9.9 supports it?

I tried 9.9.9.9, no difference. Im on starlink behind cgnat, so maybe it wont work period?

**Comment by rany2** [comment]
Some ISPs filter out ICMP timestamps, so I'm not surprised. Stick to fping.

**Comment by lynxthecat** [comment]
Ah yes. I think we figured out that Starlink filters out ICMP type 13.

**Comment by LiveWire1968** [comment]
> Ah yes. I think we figured out that Starlink filters out ICMP type 13 - see here:
> 
> https://forum.openwrt.org/t/cake-w-adaptive-bandwidth-historic/108848/3036

Thanks, it really didnt take me long to get around the meson/ninja stuff. I just built the binary on the router. cake-autorate doesnt seem to work well for me with Starlink, so thought Id play, try some options again.

**Comment by lynxthecat** [comment]
I think it likely just needs some configuration as the defaults are set for 4G. You’d be welcome to post on the OpenWrt cake-autorate thread (ideally with log file covering two or three speed tests) and we can work out the optimal settings.
