### ISSUE TITLE
bash question

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/CAKE-autorate#27]
https://github.com/lynxthecat/CAKE-autorate/blob/ff783c97c0765a7af7f5cd785897e33a18c9e24f/CAKE-autorate.sh#L265

How is that working
```
get_max_wire_packet_size_bits $dl_if dl_max_wire_packet_size_bits  
get_max_wire_packet_size_bits $ul_if ul_max_wire_packet_size_bits
```

and

```
get_max_wire_packet_size_bits()
{
	local interface=$1
	local -n max_wire_packet_size_bits=$2
 
	read -r max_wire_packet_size_bits < "/sys/class/net/${interface}/mtu" 
	[[ $(tc qdisc show dev $interface) =~ (atm|noatm)[[:space:]]overhead[[:space:]]([0-9]+) ]]
	[[ ! -z "${BASH_REMATCH[2]}" ]] && max_wire_packet_size_bits=$((8*($max_wire_packet_size_bits+${BASH_REMATCH[2]}))) 
	[[ "${BASH_REMATCH[1]}" == "atm" ]] && max_wire_packet_size_bits=$(( 424*(($max_wire_packet_size_bits+376)/384) ))
}
```

I am not firm enough in shell, but I fail to see where dl_max_wire_packet_size_bits and ul_max_wire_packet_size_bits are actually assigned? I naively expect either an `echo ${max_wire_packet_size_bits}` in get_max_wire_packet_size_bits() and 
`dl_max_wire_packet_size_bits =$( get_max_wire_packet_size_bits $dl_if  )`
or an `eval` that assigned the value to the global variable referenced in max_wire_packet_size_bits, but again I am not a bash expert.

**Comment by lynxthecat** [comment]
Bash now supports passing by reference, and the way you do this is as follows.

Within function definition:

`local -n max_wire_packet_size_bits=$2`

And then when calling function (consider the omission of the $ in the passed by reference variable):

`get_max_wire_packet_size_bits $dl_if dl_max_wire_packet_size_bits `

https://stackoverflow.com/questions/540298/passing-arguments-by-reference

**Comment by moeller0** [comment]
SWEET! I dislike the way this looks a bit (XXX=$(( fn_do_something $input1 "test" )) ) nicely documents what are inputs and what are outputs, but this gives immense power and might even allow multiple return values, while keeping echo clean to be used for debugging output.

That said, I had tried to search for "bash local -n" and came up blank.

**Comment by lynxthecat** [comment]
Yes it does allow multiple return values! See here:

https://github.com/lynxthecat/CAKE-autorate/blob/main/CAKE-autorate.sh#L41

bash is super cool!

**Comment by moeller0** [comment]
Sweet again!
