### ISSUE TITLE
Add AsusWRT support

### ISSUE THREAD

**Issue by LiveWire1968** [lynxthecat/cake-autorate#270]
@lynxthecat  I see she-bangs were just changed, if you care about updating your setup script for asus also..
/etc/OS-release does not exist, but uname -a will output ASUSWRT-Merlin.
Only changes is scripts go in /jffs/scripts, config files should be in /jffs/configs ,mine still sits in /jffs/scripts.
logs go in /tmp
then 
dl_if=ifb4eth0 # download interface
ul_if=eth0     # upload interface
I believe thats really all of it.
But the user would still need to make sure opkg packages are installed

**Comment by lynxthecat** [comment]
@rany2 do you suppose it might be an idea to add support for Asus Merlin with extra setup options? I don’t suppose you might be motivated to do so? I would understand entirely if not. Neither of us even have Asus Merlin. But it’s a very friendly community and there are a fair number of users.

**Comment by rany2** [comment]
@lynxthecat shouldn't be much effort, I'll make a PR and ping @LiveWire1968 to test it

**Comment by rany2** [comment]
@LiveWire1968 opkg is available as part of entware and the packages are the same between asuswrt and openwrt; right?

**Comment by LiveWire1968** [comment]
> @LiveWire1968 opkg is available as part of entware and the package names cake-autorate needs are the same between asuswrt and openwrt; right?

opkg is part of entware, packaged needed installed are  bash iputils-ping fping coreutils-mkfifo

**Comment by rany2** [comment]
Fyi mkfifo isn't needed anymore.

**Comment by LiveWire1968** [comment]
![image](https://github.com/lynxthecat/cake-autorate/assets/76123941/a9618fda-2d84-42fb-8440-8352d9456fe7)

Only ways i see to determine Asus

**Comment by LiveWire1968** [comment]
> @LiveWire1968 opkg is available as part of entware and the package names cake-autorate needs are the same between asuswrt and openwrt; right?
I havent had time to really mess with it, but asus bash does not like launcher.sh at all. I just changed it to below for now, does same thing though?

#!/usr/bin/env bash
killall cake-autorate.sh
sleep 2s
/jffs/scripts/cake-autorate.sh

**Comment by rany2** [comment]
@LiveWire1968 does `uname -o` also return ASUSWRT-Merlin?

**Comment by rany2** [comment]
> but asus bash does not like launcher.sh at all

what bash version is this?

**Comment by LiveWire1968** [comment]
@rany2  uname -o does show ASUSWRT-Merlin
Bash version
GNU bash, version 5.2.15(1)-release (aarch64-openwrt-linux-gnu)

**Comment by rany2** [comment]
@LiveWire1968 Are you still available if I were to make changes now?

**Comment by rany2** [comment]
I'm a bit more ambitious and want cake-autorate to switch to `/jffs` on its own in the main script.
