### ISSUE TITLE
Sleep?

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/CAKE-autorate#29]
https://github.com/lynxthecat/CAKE-autorate/blob/b393c101cbc7cbe2d30b67cf8918564cbd868f75/CAKE-autorate.sh#L381

If this is a replacement for a sleep call, I think moving this into a dedicated function with an appropriate name will make the code easier to read, and also gives a plce to comment that this approach seems to be "cheaper" than actually using the sleep built-in.

**Comment by lynxthecat** [comment]
Fixed with: 

https://github.com/lynxthecat/CAKE-autorate/commit/dc744a6f319fdab39b7495eb5b4544a2ff72863f
