### ISSUE TITLE
Following installation instructions on OpenWrt - Error: bash is required, please install it and rerun the script!

### ISSUE THREAD

**Issue by boktai1000** [lynxthecat/cake-autorate#306]
Running the installation via https://github.com/lynxthecat/cake-autorate/blob/master/INSTALLATION.md

This is on OpenWrt Official 23.05.3 - Hardware Banana Pi R3

```
root@HaroWrt:/tmp# wget -O /tmp/cake-autorate_setup.sh https://raw.githubusercon
tent.com/lynxthecat/cake-autorate/master/setup.sh
Downloading 'https://raw.githubusercontent.com/lynxthecat/cake-autorate/master/setup.sh'
Connecting to 2606:50c0:8003::154:443
Writing to '/tmp/cake-autorate_setup.sh'
/tmp/cake-autorate_s 100% |*******************************|  8648   0:00:00 ETA
Download completed (8648 bytes)
root@HaroWrt:/tmp# sh /tmp/cake-autorate_setup.sh
bash is required, please install it and rerun the script!
root@HaroWrt:/tmp#
```

![image](https://github.com/lynxthecat/cake-autorate/assets/9054563/d0fa1d1d-0642-4a13-931a-2c06f1bcd4d0)

The only pre-req I see mentioned is the installation of `luci-app-sqm` which I have installed and configured.

I'm not sure if it's a problem with the installation script, or the documentation needs to be more descriptive about pre-reqs, or another step - but either way heads up! Thank you for the script - I can't wait to get it working!

**Comment by lynxthecat** [comment]
Yes there are a couple of packages like bash and fping that are required. I removed the automatic installation of those on the basis that users may not like that. Yes the documentation should be updated to reflect these requirements.
