### ISSUE TITLE
Installation instructions of v3.2 branch links to "master" script instead of "v3.2" script.

### ISSUE THREAD

**Issue by ffrrzz** [lynxthecat/cake-autorate#316]
The install instructions here seem to link to the wrong script: https://github.com/lynxthecat/cake-autorate/blob/v3.2/INSTALLATION.md

> Use the installer script by copying and pasting each of the commands below. The commands retrieve the current version from this repo:
> 
> wget -O /tmp/cake-autorate_setup.sh https://raw.githubusercontent.com/lynxthecat/cake-autorate/master/setup.sh
> sh /tmp/cake-autorate_setup.sh

**Comment by rany2** [comment]
Thanks, fixed in v3.2 branch.
