### ISSUE TITLE
Feature request: allow cake-autorate measure/apply different cake parameters with different country(s) ip

### ISSUE THREAD

**Issue by ajdgsu** [lynxthecat/cake-autorate#323]
When I trying to connent local countrues ip, the lantency & speed are around 30ms & 500mbps. But when I trying to connent foreign countries ip, the lantency & speed can easily drop to 300ms & 10mbps. Both slow and fast connections can happen at the same time, so it would be nice to have separate cake parameters
 based on different countries ip.

I think we can use geoip to analyze ip https://github.com/v2fly/geoip, or more serious can use maxmind geoip(require a free account to download): https://dev.maxmind.com/geoip/geolite2-free-geolocation-data

**Comment by rany2** [comment]
This is an issue with your ISP or downstream of your ISP and not something that cake-autorate can fix in a straightforward way. At any rate, this setup would be possible with an nftables ruleset that marks packets depending on whether they're local or foreign...you can then create two (or four if you want a DL queue too) CAKE queues and have cake-autorate manage both by running multiple instances of it.
