### ISSUE TITLE
Instrumenting CAKE-autorate to learn more about underlying links

### ISSUE THREAD

**Issue by richb-hanover** [lynxthecat/cake-autorate#33]
Here's an ill-formed thought to throw out for the collective wisdom to consider:

At this point, CAKE-autorate appears to be doing a great job of maximizing transfer rates while minimizing latency. It does this by adjusting the CAKE parameters to provide good service to its human masters :-) This is good.

Speculation: What would it mean to use CAKE-autorate "backwards" - to characterize the speed of the underlying links. I've heard a bunch of assertions about various link technologies:

- I believe a fiber optic connection runs very stably at/near the ISP's rated speed
- I suspect that DSL/VDSL also similar stable data rates
- It is widely believed that Cable Modem speeds exhibit 'sag' in the high-traffic evening hours
- Cellphone modems offer wildly differing data rates over time. Is there any pattern to them?
- Starlink - there's a reason to think it might have a 15-minute periodicity in its speeds. 

But I don't know of an existing consistent/reliable way to measure/confirm any of the above assertions.

My Challenge:

- CAKE-autorate is continually adjusting the CAKE parameters. Would it be useful to examine this information over a long term?

- If so, how could we sample the readings in a useful, sufficiently granular way to display "what's going on" with the underlying link? 

- How could we make sense of the data without being drowned in multiple data samples per second?

Possible Use Case: Add a "CAKE Link-Speed" tab to the Realtime Graphs page that showed [ indication of the link speeds | variation in the link speeds ] over time.

Thanks!

**Comment by moeller0** [comment]
Interesting thought. I guess the sampling is going to be uneven, as we could only use samples from 100 load just before a delay spike that forces us to throttle down? These probably should be binned in say blocks of say 5-15 minutes and collected and displayed for a full week.

**Comment by moeller0** [comment]
Interesting thought. I guess the sampling is going to be uneven, as we could only use samples from 100 load just before a delay spike that forces us to throttle down? These probably should be binned in say blocks of 15 minutes and collected and displayed for a fu

**Comment by richb-hanover** [comment]
> I guess the sampling is going to be uneven...

I have always wondered about some kind of "differential mode" for the logs that only displays information when CAKE-autorate "steps on the brakes or the accelerator". For stable links, it might help to have a periodic (once per minute? per 15 minutes?) "current state" log message to make it easier to know the conditions before a change occurred.

**Comment by lynxthecat** [comment]
How about a separate helper script that starts up CAKE-autorate then loads up the connection and records the stats and then reports the bandwidth and latency stats?

**Comment by richb-hanover** [comment]
I wonder if this could be implemented as a modification to the `output_cake_changes` logging. Maybe log lines could include:

- current time stamp
- interface
- delay/latency immediately before (that caused?) the change to the cake setting
- new bandwidth setting
- what other information would be interesting?

**Comment by richb-hanover** [comment]
I'm going to close this for now. I'm investigating this for a couple weeks and will report back if I learn anything interesting.
