### ISSUE TITLE
script stops working -- pinger_0_fifo: File exists error

### ISSUE THREAD

**Issue by nahall** [lynxthecat/cake-autorate#34]
Hello,

The script has given me issues when it is running for an extended period of time. Twice now, after it has been running for some number of days, it has stopped adjusting the rates. The script is still running, but there are errors logged to /tmp/cake-autorate.log:

> mkfifo: /tmp/CAKE-autorate/pinger_0_fifo: File exists
> mkfifo: /tmp/CAKE-autorate/pinger_1_fifo: File exists
> mkfifo: /tmp/CAKE-autorate/pinger_2_fifo: File exists
> mkfifo: /tmp/CAKE-autorate/pinger_3_fifo: File exists
> mkfifo: /tmp/CAKE-autorate/pinger_4_fifo: File exists
> /root/CAKE-autorate/CAKE-autorate.sh: line 178: /tmp/CAKE-autorate/pinger_1_fifo: No such file or directory
> mkfifo: /tmp/CAKE-autorate/pinger_0_fifo: File exists
> mkfifo: /tmp/CAKE-autorate/pinger_1_fifo: File exists
> mkfifo: /tmp/CAKE-autorate/pinger_2_fifo: File exists
> mkfifo: /tmp/CAKE-autorate/pinger_3_fifo: File exists
> mkfifo: /tmp/CAKE-autorate/pinger_4_fifo: File exists
> mkfifo: /tmp/CAKE-autorate/pinger_5_fifo: File exists

Then the mkfifo File exists error keeps repeating over and over, I think it outputs once per minute.

I have to first notice that there is a problem, then restart the script for it to be fixed.

Do you have any ideas of why this could be happening? Thanks!

**Comment by nahall** [comment]
Could be a coincidence, but this time that I noticed the problem was after my internet was out for several minutes.

**Comment by nahall** [comment]
Yes OpenWrt 21.02.3 r16554-1d4dea6d4f. I already killed the processes but next time it happens I can check that.

**Comment by lynxthecat** [comment]
Has the issue reoccurred?

**Comment by nahall** [comment]
Not yet

**Comment by lynxthecat** [comment]
And now (assuming you are still running this!). Would be good if you can verify there are no extra stale ping instances running using top / ps.

**Comment by nahall** [comment]
Still working!

**Comment by lynxthecat** [comment]
Out of curiosity what's your use case? Did you change the configuration options much? Any changes you can think of?

**Comment by nahall** [comment]
I'm gba on the forum. So Starlink :-) And yes it's continued to work well for me, I haven't changed anything in the past month.

**Comment by lynxthecat** [comment]
Ah, great. Will mark this as close for now then. And thanks for your detailed input and analysis earlier that helped me to make this project better.
