### ISSUE TITLE
Tweaks to CAKE-autorate?

### ISSUE THREAD

**Issue by richb-hanover** [lynxthecat/cake-autorate#35]
I'm thinking of making some tweaks to the CAKE-autorate repo and want to know if they would be seen as useful/helpful. Specifically:

- **Create an installer script** 
	- I screw up about half the time when I do a fresh install - a script will help
	- I'll figure out how to handle the situation when there's an existing configuration

- **Configuration file**
	- Rename the config file to "CAKE-config.sh" to match its partner "CAKE-autorate.sh"
	- Add Version number in CAKE-config.sh. That will help with bug reports, etc. I would probably call the current version "1.0.0" since it's working well, and there's little churn now.

- **Changes to logging**
	- Output a startup message with Version, interfaces used
	- Implement the `output_cake_changes` message as suggested in #33 (I already tried this, and it looked interesting)
	- Document where log messages go

- **Update the README** to reflect all this

Would this be helpful? Any other thoughts? I'm happy to make a PR over the next week or two. Thanks.

**Comment by lynxthecat** [comment]
These all seem like positive changes to me. 

Ultimately it would be good to get this made into an OpenWrt package and config file set with UCI integration, but I lack the knowhow to implement that properly.

**Comment by richb-hanover** [comment]
Thanks for the encouragement. (Yes, an OpenWrt Package would be cool. But one insurmountable hurdle at a time... :-)

As I play with an installer script, I will bump into questions. My first:

* When it's run as a service, log messages seem to go into `/tmp/cake-autorate.log`  
* Where do messages go when CAKE-autorate is run manually e.g., `bash ./CAKE-autorate.sh`

**Comment by lynxthecat** [comment]
I think they then just get presented on the terminal from which the user runs the command.

**Comment by richb-hanover** [comment]
> I think they then just get presented on the terminal from which the user runs the command.

Yes. I see that now. Thanks.

**Comment by richb-hanover** [comment]
Another question: One of my long term goals is #33 - to find a way to log only the changes to the CAKE parameters. Toward that end, I have updated the code in set_cake_rate() to show the values used when calling tc to change the CAKE parameters.

But that's not the part that interests me... I want to know what is "happening" prior that call - what are the previous & current delay measurements, %utilization, other factors that force a change to the CAKE parameters.

I haven't spent much time with that part of the code. It would be great if you could point out where those decisions are being made, and which variables might be interesting: delay values, etc.

**Comment by lynxthecat** [comment]
Cake updates can be output by setting:

`output_cake_changes=1`

in the config. 

The decisions are made here:

https://github.com/lynxthecat/CAKE-autorate/blob/405d91060d70ba7edf02ab5b6acfe7263fe2494e/CAKE-autorate.sh#L34

Based on the load condition classified here:

https://github.com/lynxthecat/CAKE-autorate/blob/405d91060d70ba7edf02ab5b6acfe7263fe2494e/CAKE-autorate.sh#L151

Output lines look like this when enabled:

https://zerobin.net/?2363c252a201c3af#D34t05AAIBbAaBbctQ0N7RVmuPbUyEcq5Ge//Ye/cY4=

And correspond with:

https://github.com/lynxthecat/CAKE-autorate/blob/405d91060d70ba7edf02ab5b6acfe7263fe2494e/CAKE-autorate.sh#L610

Those can be plotted like here:

https://forum.openwrt.org/t/cake-w-adaptive-bandwidth/108848/3181?u=lynx

**Comment by richb-hanover** [comment]
Cool! This is exactly the explanation I was looking for. Thanks.

**Comment by lynxthecat** [comment]
Marking as closed since your excellent suggestions have all been mostly implemented. On my to do list is to use the log message function for all output. Thanks again.
