### ISSUE TITLE
Please add compatibility with mwan3

### ISSUE THREAD

**Issue by patrakov** [lynxthecat/cake-autorate#36]
I tried to use CAKE-autorate together with mwan3, and found two issues.

The first issue is that CAKE-autorate.sh script runs `ping` without specifying an interface. This means that ICMP packets are routed according to the routing table. However, this might be wrong in some cases involving multiple uplinks, e.g. VPN (when we want to use the non-VPN connection to monitor the modem-induced bufferbloat).

Please add the `-I ${ul_if}` parameter to each ping invocation. Or maybe add a separate configuration parameter that specifies the interface to use as the outgoing interface for pings, defaulting to `${ul_if}`.

The second potential issue is that someone (not me) might want to run the script with two LTE modems from different operators, load-balnced with mwan3, and thus might want to run several instances. Maybe it's a good idea to accept a command-line parameter that specifies the config.sh file to use, and make sure that the pinger FIFOs and other files don't collide between multiple script instances.

**Comment by patrakov** [comment]
Well, specifying the interface is not 100% OK: for some reason, the first few pings are not even sent out (and thus detection of alive reflectors fails unless I adjust the timeout). Specifying the source IP instead of the interface works better - but the script should get it from the interface when starting a pinger, e.g. like this:

```
src_ip=$(ip -o -4 addr show dev wwan0 | grep -o 'inet [0-9.]*' | head -n 1 | sed 's/inet //') || src_ip=0.0.0.0
[[ $(ping -I ${src_ip} -q -c 5 -i 0.1 ${reflectors[$pinger]} | tail -1) =~ ([0-9.]+)/ ]] && printf ...
```

**Comment by richb-hanover** [comment]
This is a really sexy idea. And it makes sense, too - each interface could be responsible for minimizing its own queued data. But I believe it's an interesting (e.g., difficult) implementation/configuration challenge. At first blush, you'll need:

- Separate SQM QoS instances on each of the mwan3 interfaces
- Separate instances of the `autorate` code running for each of the mwan3 interfaces
- I don't know much about mwan3 and the dynamics of sharing load across multiple interfaces. Is there a way for a sub-interface to offer a hint about slowing down? Or should the CAKE instance on a particular interface just handle the throttling of any particular flow?

I'm pretty sure this isn't going to be "just a tweak" to the code. (But I would be delighted to be proved wrong :-)

**Comment by patrakov** [comment]
> How about just having the user set source IP for ping in the config.sh?

Can't work - it's dynamic and can even change during the lifetime of the script due to reconnections (and this would probably result in restarting the pinger because the source IP no longer works, and thus the reflector "no longer works").

**Comment by patrakov** [comment]
> * Separate SQM QoS instances on each of the mwan3 interfaces

Well, only those that need it.

> * Separate instances of the `autorate` code running for each of the mwan3 interfaces

Correct.

> * I don't know much about mwan3 and the dynamics of sharing load across multiple interfaces. Is there a way for a sub-interface to offer a hint about slowing down? Or should the CAKE instance on a particular interface just handle the throttling of any particular flow?

The mechanics is that for each TCP connection or UDP stream, an uplink connection is assigned automatically through policy-based routing. While adjusting the weights automatically based on achieved rates seems like a nice idea, let's not do it, because (well, this is the first thing that comes to my mind) of the positive feedback loop that would just shift all the load to one connection. Anyway we are talking just about compatibility (i.e. using the right outgoing interface/ip when probing the bufferbloat on each interface), not integration.

**Comment by lynxthecat** [comment]
Seems to make sense to me that leverage the data you can get from CAKE-autorate in terms of working out which connection to use. Like CAKE-autorate gives you a lot of info about the bandwidth and latency of a given connection. You could presumably set some rules to dictate when to switch in dependence upon latency and load, no?

**Comment by patrakov** [comment]
Yes. But not now. Let's pursue mere compatibility (using the correct interface and not clashing) first in this ticket.

Adjusting uplink choice and load-balancing policies should be a separate ticket, especially because I can't yet meaningfully test such setups. Also, I already mentioned the feedback loop that makes me think that the idea with switching rules is not implementable: if we choose one connection as the preferred one, then the other one won't be used, its shaper speed won't be increased, and thus we will never know that it is in fact faster.

**Comment by patrakov** [comment]
EDIT: a better command to get the correct source IP might be something like this - not sure:

```
root@OpenWrt:~# ip route get 8.8.8.8 dev pppoe-wan
8.8.8.8 via 10.205.78.123 dev pppoe-wan src 10.40.57.91 uid 0 
    cache 
root@OpenWrt:~# ip route get 8.8.8.8 dev wwan0
8.8.8.8 via 10.170.34.41 dev wwan0 src 10.170.34.44 uid 0 
    cache 

```

**Comment by moeller0** [comment]
> * Separate SQM QoS instances on each of the mwan3 interfaces

That is already possible with SQM out of the box, the only limit is per interface only one SQM instance.

**Comment by lynxthecat** [comment]
I thought about this further. Why not just use two IFBs and direct flows using fwmarks as appropriate and keep cake instances and cake-autorate running? See my cake-dual-ifb repository for inspiration about how to filter on fwmarks and redirect to IFBs.
