### ISSUE TITLE
missing fping seems not to be detected...

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#41]
Just tried with the next-generation branch set for fping, but without fping installed.
Instead of an abort with an error message the errors just keep on piling on.

**Comment by lynxthecat** [comment]
Oh good point. Best way to check for that?

**Comment by moeller0** [comment]
Maybe something like `type fping` might work:
```
laptop:~ user$ type fping
fping is /usr/local/bin/fping
laptop:~ user $ type fping5
-bash: type: fping5: not found
laptop:~ user $ 
```
Since we use bash already maybe check whether `type -t $BINARY` returns file (or rather whether it is not empty):
```
user@Linux:~$ type -t fping
user@Linux:~$ type -t ping
file
user@Linux:~$ type -t echo
builtin
user@Linux:~$ 
```

**Comment by lynxthecat** [comment]
Fixed here: https://github.com/lynxthecat/cake-autorate/commit/4bab92aa435b56d529da31cddfbda837853ab416

**Comment by moeller0** [comment]
Fair enough! Great! Will test later this week.
