### ISSUE TITLE
Missing log

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#42]
When started on a terminal I do not seem to get a log file...
I tried to fix that by making the log file creation independent of whether things run on the terminal or not.

**Comment by moeller0** [comment]
So what I think would be nice is to have two toggles:
`log_to_console`
and 
'log_to_file`
that can both be activated simultaneously, the current logic about detecting a console should still be used for log_to_console, while log_to_file should be usable independently, so that it is easy to generate nice log files even when starting/stpping from the console.
I started hacking this but stopped after realizing that nano on my router is not the best tool for that job, and I ran out of time...

**Comment by lynxthecat** [comment]
Good idea. I've enabled with: https://github.com/lynxthecat/cake-autorate/commit/0ebe150017216a1c5aa3f078ce286a64d716c125 and https://github.com/lynxthecat/cake-autorate/commit/3be0e99181afc9837b544bc3c03cd643769ad6e7.
