### ISSUE TITLE
du -b option is not implemented in (older) busybox's du 

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#43]
Installing coreutils-du fixed that issue, but do we really require a separate install for this?

**Comment by lynxthecat** [comment]
No; now I just track bytes based on size of string to write and it seems to work fine.

**Comment by moeller0** [comment]
Well, it is not guaranteed to be fine:
a) on disk size and size written is typically not identical (but might be for a ramdisk)
b) different text encodings also break the one character one byte rule that holds for ascii

None of the above might trigger on your system, but can we be sure that this is also true for all users' systems?

IMHO doing prediction is fine, if that prediction is verified ever so often like every 100 or every 1000 lines written by getting the true on disk size (getting that number immediately solves potential issues a) and b) above). But then I fail to see the big utility in limiting individual log file size if the goal is to avoid OOM, as in that case the relevant number is not individual log file size but "free space" and that can not be tracked by just monitoring our own write sizes anyway. ;)

But all of that is orthogonal to the use of the `-b` command line argument which might be avoided by simply keeping the size threshold in KB as well as du seems to report KB by default. (I would assume KiB so base2^10 and not true KB base10).

**Comment by lynxthecat** [comment]
So it's on /tmp and why would there be different text encodings? du -b is needed because that reports 'apparent size' and otherwise the results seemed wrong.

**Comment by moeller0** [comment]
> So it's on /tmp and why would there be different text encodings?

Because a user might use the default UTF-8 encoding, so all that is needed is some non asci caracters somewhere and the assumption 1 byte per character/glyph is wrong.



> We always write ASCII so it's one-byte per character, right?

Consciously yes, but are we sue that there is no way we get something else logged? I would not bet on this.



> du -b is needed because that reports 'apparent size' and otherwise the results seemed wrong.

Exactly not, --apparent-size is NOT the size on disk, but if the goal is to limit the file system cost of the log files to avoid OOM we need the on-disk size.

**Comment by lynxthecat** [comment]
I remembered now it was just because I was testing 'du' using sparse files and comparing against what was reported using 'ls -l' 

The user would have to change the code to write anything other than ASCII out and I don't think we need to cater for this? Everything we write out is controlled and ASCII.

**Comment by moeller0** [comment]
> I remembered now it was just because I was testing 'du' using sparse files and comparing against what was reported using 'ls -l'

Even then the on disk size is all that matters for avoiding OOM, really. And I can almost guarantee that we will not have sparse log files, as I think our writing method can not produce sparse files. While we do have little control over a users charcter encoding choice...



> In terms of log messages generated in the code, the user would have to change the code to write anything other than ASCII out and I don't think we need to cater for this? Everything we write out is controlled and ASCII.

Yes we do, 1 character one byte is not a generically viable approximation anymore, so let's not use that as we know it has some nasty failure modes which we can easily avoid. ;) Better safe than sorry.



> stdout/stderr could be non-ASCII I suppose? Since I redirect those to the fifo so I guess this could give issues.
> 
> ... wait we can just force UTF-8 right?

Which does not help, as a single character/glyph in UTF-8 can be anything from 1 to 4 byte in length. Yes the first 128 ASCII characters map onto a single UTF-8 byte, but again unless we have full control we can not guarantee that will hold for all users.

Really why this is a big issue at all? Maybe you tell me what your goal is with the log file size limitation and we can then discuss suitable implementations? ATM I am clearly confused why we do all of this and hence my comments might be less than helpful in achieving our goals.

To repeat myself, I consider size limited log files a secondary optimization and personally prefer time limits more (as these are easier to reason about: "does this log file contain the traces of that weird network experience my family told me experiencing for the last hours before I came home?") And for OOM purposes, all that matters are size-on-storage or rather usable free space on storage.
But as I said before doing a size growth prediction even based on the 1 char 1 byte rule seems an acceptable heuristic assuming we occasionally bring the prediction onto alignment with the true on storage sizes.

Now, if the problem is that Excel only works acceptably well with log files up to X MB that would be a different constraint ;)

**Comment by lynxthecat** [comment]
So is this statement not correct then?

> The C locale is a special locale that is meant to be the simplest locale. You could also say that while the other locales are for humans, the C locale is for computers. In the C locale, characters are single bytes, the charset is ASCII (well, is not required to, but in practice will be in the systems most of us will ever get to use), the sorting order is based on the byte values¹, the language is usually US English (though for application messages (as opposed to things like month or day names or messages by system libraries), it's at the discretion of the application author) and things like currency symbols are not defined.

Can we get non one byte per character characters with:

`export LC_ALL=C`

**Comment by moeller0** [comment]
Well, when I set LC_ALL=C I still see UTF-8 encodings in use so the problem is still there (assuming my quick testing was valid).
Still puzzled why we are discussing this, assuming 1 char = 1 byte is simply not precise anymore in a wold where UTF-8 is the default encoding. There will be controlled conditions in which it still holds true but it clearly is not generically true anymore*, but unless there is a really compelling reason to require this, I think it is best to avoid making that assumption. 
In the specific case I think there is not real justification for not occasionally checking against the true on-storage-size, and I think if we do that occasionally "risking" underestimating the true size for some lines written is not a big deal. However the potential fr underestimation of the true size leaves me unconvinced that pure "predictive" size determination is robust and reliable.


> To me it makes sense for user to specify max size of log file. I can't explain why. It's similar to max time. It just feels right.

Your project, your choice (as I said as maintainer/creator you have the privilege and onus to make these decisions).

> It seems printf can be forced to output one byte characters with '%c' (LC_ALL=C forces this to one byte per character) but that would then require for loop over the string.

Can you explain why you seem to be fundamentally opposed to occasionally checking true size? If you do that rarely enough the run time cost will be minimal, but you can be sure that any prediction error will likely be small enough to be ignorable...


*) BTW this was one of the non-backward compatible differences between python2  and python3, getting rid of the assumption that 1 character equals 1 byte in a string.

**Comment by lynxthecat** [comment]
OK I just checked:

`((log_file_size_bytes=log_file_size_bytes+${#log_line}+1))`

counts bytes consumed. So it seems to be doing the right thing?

**Comment by moeller0** [comment]
> So actually even if characters consume more than one byte it will still work - unless I'm missing something?

Yes this looks like a) UTF-8 does throw off the 1 char = 1 byte assumption as we discussed even if `LC_ALL` is set to `C` and b) bash seems to be smart about this*. This looks like another argument why bash was a decent choice to base the implementation on.

However, even if this should be true for all instances of bash running autorate, I still recommend to actually check the on disk usage, because that really seems to be the relevant number here. Heck if you are really concerned about sparse files do:
```
max(log_file_size_bytes, $(( du -b ${fully_qualified_log_file_name ))
```
I am pretty sure sparse files will not be an issue (not sure tmpfs/ramfs actually supports sparse files), so the latter will likely be >= the former, but "better safe than sorry" applies here as well.



*) Unless you are actually interested in aligning glyphs in a printout, say to align table columns and the header contains muti-byte chars. But that is not our issue so can be ignored. Also bash being bash there likely is a way to get to the length of the character sequence as well somehow.

**Comment by lynxthecat** [comment]
Yes so you were right in that LC_ALL=C does not mean one byte per character, but it does seem to make bash behave how I want it to with counting bytes per string. 

You think running with:

`((log_file_size_bytes=log_file_size_bytes+${#log_line}+1))`

is too dangerous and rather we should instead every X lines just call 'du' without '-b'?

**Comment by moeller0** [comment]
No, I think your prediction of file size is a pretty nice optimisation and I would carry on doing it, however every say 1000 writes I would use du to confirm the on storage size and set log_file_size_bytes to that value, or split these out into:
log_file_size_KB
current_log_file_size_Byte
feed log_file_size_KB from `du -k` and current_log_file_size_Byte from within the script, and reset this to 0 on calls to du and do the comparison for when to rotate the log with `$(( ${log_file_size_KB} + ( ${current_log_file_size_Byte} / 1024 ))`
but that might be overdoing things...

**Comment by lynxthecat** [comment]
So I've amended the config file documentation to specify:

```
# ** Take care with these settings to ensure you won't run into OOM issues on your router ***
# every write the cumulative write time and bytes associated with each log line are checked
# and if either exceeds the configured values below, the log log file is rotated
log_file_max_time_mins=10 # maximum time between log file rotations
log_file_max_size_KB=2000 # maximum KB (i.e. bytes/1024) worth of log lines between log file rotations
```

**Comment by moeller0** [comment]
Maybe worth mentioning that only one rotated log will be kept.
And for avoiding OOM really we are not doing the best we can, we really would need to look at available storage space. Because for OOM it does not matter if we even just wrote a single byte to a log file, as kong as that byte pushed us over the limit. Note on a normal filesystem running out of space will be primary just that no more space to write, it is only for ramdisks where out of storage space can result in out of memory. Not that out-of-storage-space is a fun condition to run into.
So the current measures are for avoiding excessive logging and basically allowing the log to run continuously in "flight recorder" mode that can be evaluated after crashes or observed wonky behavior.

**Comment by lynxthecat** [comment]
So we use something like this:

```
root@OpenWrt:~# { read x; read y; } </proc/meminfo
root@OpenWrt:~# echo $y
MemFree: 314624 kB
```

**Comment by moeller0** [comment]
Well, that will work on systems where log file is written to tmpfs, which seems to be correct for OpenWrt, but e.g. Debian uses a real /tmp directory on what ever storage you use. And tmpfs can be limited to less than the full ram.
If you want to check free space than `df ${logfilename}`:
```
user@Linux:~$ df /usr/bin/bash
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda5      102107096 21862228  75011972  23% /

user@Linux:~$ df --output=avail /usr/bin/bash
   Avail
75011972
```
the second invocation only returns the available size which might be the desired one. However I have not tested what this returns on tmpfs and how this deals with the situation that e.g. a tmpfs of <= 16 MB is only filled with 15 Mb but there is only 0.5MB of memory available to back this. No idea whether df returns the desired value of 0.5 or the less helpful but not technically wrong 1 MB.

**Comment by lynxthecat** [comment]
Argh. I think I'm going to mark this as closed, bury my head in the sand, and if anyone complains or any issue comes up then readdress it.
