### ISSUE TITLE
dl_xxx and ul_xxx values are always appear to be identical

### ISSUE THREAD

**Issue by richb-hanover** [lynxthecat/cake-autorate#47]
I cloned the next-generation branch into my repo, then changed the conditions for log messages so that the code only displays values when the CAKE parameters change. Here's the updated `cake-autorate.sh`: https://github.com/richb-hanover/CAKE-autorate/blob/tweak-ng-logging/cake-autorate.sh 

The attached Excel file shows the resulting log messages. 

I note that the DL_OWD_BASELINE, DL_OWD_US	, DL_OWD_DELTA_US values are always equal to the corresponding UL_xxx values. Does this make sense? Thanks.

[CAKE-autorate-log-28Sep2022.xlsx](https://github.com/lynxthecat/cake-autorate/files/9676889/CAKE-autorate-log-28Sep2022.xlsx)

**Comment by lynxthecat** [comment]
What's the motivation for that though? For diagnostic purposes it's helpful to keep track of what happens in between the changes isn't it? I suppose this could be a configurable output option? Any thoughts @moeller0?

**Comment by richb-hanover** [comment]
Yes - I want to see "what's happening" under the covers. The existing display of the `tc` parameters only says that the settings increased/decreased without showing the conditions that led to the change. I've used `$output_cake_changes` to control when to display all the data. 

But that's not my question: I'm curious that line 12 of the spreadsheet shows the same values (`10949	6000 -49490`) for the both the download and upload. Is this expected? Thanks.

**Comment by lynxthecat** [comment]
Ah yes that's normal because fping only supports RTT's and not ICMP type 13 so with the code generalised to OWDs we just split the RTT right down the middle. My hope is that either fping is updated to support ICMP type 13 or an kind soul from OpenWrt writes a C-based ping binary that supports ICMP type 13 + round robin requests so we can switch over to that.
