### ISSUE TITLE
Feature request: better message about misbehaving reflectors

### ISSUE THREAD

**Issue by patrakov** [lynxthecat/cake-autorate#48]
Right now, cake-autorate prints "Reflector X is misbehaving", with no additional details, which sounds too imprecise. I would like to have some extra details included - e.g. the relative timestamp of the last good ping, and, if known, the exact reason for the "misbehaving" decision. E.g. (completely made up): "last good ping 20 seconds ago, no responses since then".

**Comment by lynxthecat** [comment]
Good idea. I'll add such messages in like I did with the stall code.

**Comment by lynxthecat** [comment]
I've implemented extra debugging. Please reopen if still an issue.
