### ISSUE TITLE
Stopping a console statrted autorate instance seems to auto-clean the log files...

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#50]
Title says it all. It appears that stopping a console started instance will in its clean-up state also delete any log file?

**Comment by moeller0** [comment]
Maybe we can store the logs by default in /tmp/log and on start-up simply force a log rotation so that at least the previous current log get conserved as old log? This should still guarantee that we do not use more than twice the log file threshold size on storage.

**Comment by lynxthecat** [comment]
That's weird - I don't see that. Output is sent to /tmp/cake-autorate.log and eventually that is rotated to /tmp/cake-autorate.log.old. We don't log rotate on startup but we could do that?

**Comment by moeller0** [comment]
Sorry my fault, was looking at the wrong place for the log file. It does exist.

**Comment by lynxthecat** [comment]
No worries. What do you think about log rotate on startup if log file exists? At the moment we just reset .log and write out to that. Any preference?

**Comment by moeller0** [comment]
I think log rotate is a nice touch. In most cases this will not matter much, but on pilot error we give the user a second chance to exfiltrate potentially interesting log data.
I still like the idea of this operating as a flight recorder ;) always on in the background.

**Comment by lynxthecat** [comment]
OK I will check for existence of log file and if it exists issue a log rotate.

**Comment by lynxthecat** [comment]
Done. So closing now.
