### ISSUE TITLE
Move temporary files and logs to the expected places

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#51]
According to [https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/var.html](Linux Filesystem Hierarchy) we might want to consider moving:
a) /tmp/cake-autorate to /var/run/cake-autorate
b) /tmp/cake-autorate.log to /var/log/cake-autorate.log

a) seems uncontentious, for b) I am not sure whether that might interfere with system wide log rotation.

**Comment by lynxthecat** [comment]
Changing now...

**Comment by lynxthecat** [comment]
Done. Btw these are still definitely ramdisk right?

**Comment by moeller0** [comment]
On OpenWrt /var is typically symlinked to /tmp, but generally there is no guarantee the /tmp is tmpfs to begin with...

**Comment by lynxthecat** [comment]
OK well that's good enough for me. Think can close as completed this now. Please reopen if any related issue comes up.
