### ISSUE TITLE
Cake autorate contains _ not - (resulting in auto setup script not working) 

### ISSUE THREAD

**Issue by DigitalLabs420** [lynxthecat/cake-autorate#54]
Hi, 

As title indicates above, the misnaming of the config file results in the setup script not working. 

Kind regards

**Comment by DigitalLabs420** [comment]
Manually editing it works, but should be fixed soon (:

**Comment by lynxthecat** [comment]
Thanks - fixing now.

**Comment by lynxthecat** [comment]
I think this is fixed now. @DigitalLabs420 do you agree?
