### ISSUE TITLE
New logging feature

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#62]
I wonder whether we should not keep logging the achieved rates through sleep epochs? Either by reporting all delay values as "-1" or maybe cleaner by introducing a new record type load, that really just reports something like timestamp, achieved_ul, achieved_dl, and maybe the ul/dl shaper settings. And just write these from the routine that collects the data... For bonus points we can also store an appropriate header (and make sure we write this again on log rotation):
RATES; ...
H_RATES, ...

That way we would have some insight on what happens to cause sleep epochs to end?

**Comment by lynxthecat** [comment]
Good idea - I've added it here: https://github.com/lynxthecat/cake-autorate/commit/a00ab96f01efbd0e76998ec2f422ee4005e77dfe

```
DATA; 2022-10-24-17:28:04; 1666628884.645708; 1666628884.642396; 15; 20; 0; 0; 1666628884.626630; 8.8.4.4; 9; 19203; 20300; 1098; 50318; 19203; 20300; 1098; 50509; 0; 0; dl_idle; ul_idle; 40000; 25000
DEBUG; 2022-10-24-17:28:04; 1666628884.650291; Connection idle. Enforcing minimum shaper rates and waiting for minimum load.
LOAD; 2022-10-24-17:28:04; 1666628884.672581; 1666628884.671080; 15; 20; 0; 0; 10000; 5000
LOAD; 2022-10-24-17:28:04; 1666628884.873647; 1666628884.872183; 34; 26; 0; 0; 10000; 5000
LOAD; 2022-10-24-17:28:05; 1666628885.074899; 1666628885.073436; 27; 68; 0; 1; 10000; 5000
LOAD; 2022-10-24-17:28:05; 1666628885.276497; 1666628885.274681; 274; 109; 2; 2; 10000; 5000
...
LOAD; 2022-10-24-17:28:24; 1666628904.573733; 1666628904.572308; 1009; 100; 10; 2; 10000; 5000
LOAD; 2022-10-24-17:28:24; 1666628904.774868; 1666628904.773119; 6366; 108; 63; 2; 10000; 5000
LOAD; 2022-10-24-17:28:24; 1666628904.976615; 1666628904.975454; 9356; 287; 93; 5; 10000; 5000
DEBUG; 2022-10-24-17:28:24; 1666628904.979046; dl load percent: 93 or ul load percent: 5 exceeded medium load threshold percent: 75. Resuming normal operation
DATA; 2022-10-24-17:28:25; 1666628905.111561; 1666628905.110351; 9356; 287; 93; 5; 1666628905.086120; 1.1.1.1; 0; 19532; 35750; 16233; 51260; 19532; 35750; 16233; 52521; 0; 0; dl_high; ul_idle; 10100; 5050
```

**Comment by lynxthecat** [comment]
Not sure how to manage headers now though. Should I push out two headers at the top like:

DATA-HEADER; LOG_DATETIME; LOG_TIMESTAMP; PROC_TIME_US; DL_ACHIEVED_RATE_KBPS; UL_ACHIEVED_RATE_KBPS; DL_LOAD_PERCENT; UL_LOAD_PERCENT; RTT_TIMESTAMP; REFLECTOR; SEQUENCE; DL_OWD_BASELINE; DL_OWD_US; DL_OWD_DELTA_US; DL_ADJ_DELAY_THR; UL_OWD_BASELINE; UL_OWD_US; UL_OWD_DELTA_US; UL_ADJ_DELAY_THR; SUM_DL_DELAYS; SUM_UL_DELAYS; DL_LOAD_CONDITION; UL_LOAD_CONDITION; CAKE_DL_RATE_KBPS; CAKE_UL_RATE_KBPS

LOADHEADER; LOG_DATETIME; LOG_TIMESTAMP; PROC_TIME_US; DL_ACHIEVED_RATE_KBPS; UL_ACHIEVED_RATE_KBPS; DL_LOAD_PERCENT; UL_LOAD_PERCENT; DL_LOAD_CONDITION; UL_LOAD_CONDITION; CAKE_DL_RATE_KBPS; CAKE_UL_RATE_KBPS

**Comment by lynxthecat** [comment]
> Yes sounds fine,, but can we use DATA_HAEDER and LOAD_HEADER instead? These will work directly as octave variable names while DATA-HEADER gets misinterpreted as DATA minus HEADER throwing an error since subtraction is not defined for strings...

Will do. 

> I would have left dl_load_condition naively out of the load report, but if the load function evaluates this then putting it in the record seems fine. I note that not having looked into the code (off on a lab meeting this week) I think these LOAD records should be written independent of the sleep mode so that the plotting function can get the full load data just from parsing the LOAD records. It is fine IMHO to keep the load values also in the DATA records so these still document everything for easy consumption by a human reader/debugger.

Ah, another nice idea. How often should load records be written? At the moment dl_achieved_rate_kbps and ul_achieved_rate_kbps are updated inside a perpetual while loop that does not have visibility of the shaper rates. We could ditch printing out the shaper rates and load percentages and just write out the achieved rates at the load determination frequency. Or I could instead write out the load with shaper rates and percentages inside get_loads() which is called by the main loop and the sleep loop.

**Comment by moeller0** [comment]
> How often should load records be written?

Whenever they are updated, together with the timestamp of the sampling...



> We could ditch printing out the shaper rates and load percentages and just write out the achieved rates at the load determination frequency. Or we could instead write out the load with shaper rates and percentages inside get_loads() which is called by the main loop and the sleep loop.

If the load function really only knows the most recent ul and dl traffic rates for the last interval than just write those, we can easily get the shaper settings from the DATA records, the only thing that does change during sleep are the achieved rates anyway, no?



> > Yes sounds fine,, but can we use DATA_HAEDER and LOAD_HEADER instead? These will work directly as octave variable names while DATA-HEADER gets misinterpreted as DATA minus HEADER throwing an error since subtraction is not defined for strings...
> 
> Will do.
> 
> > I would have left dl_load_condition naively out of the load report, but if the load function evaluates this then putting it in the record seems fine. I note that not having looked into the code (off on a lab meeting this week) I think these LOAD records should be written independent of the sleep mode so that the plotting function can get the full load data just from parsing the LOAD records. It is fine IMHO to keep the load values also in the DATA records so these still document everything for easy consumption by a human reader/debugger.
> 
> Ah, another nice idea. How often should load records be written? At the moment dl_achieved_rate_kbps and ul_achieved_rate_kbps are updated inside a perpetual while loop that does not have visibility of the shaper rates. We could ditch printing out the shaper rates and load percentages and just write out the achieved rates at the load determination frequency. Or we could instead write out the load with shaper rates and percentages inside get_loads() which is called by the main loop and the sleep loop.
> 
> And I presume I should add another toggle for outputting or not outputting loads stats?

I would log these unconditionally, yes they will increase the log volume a bit, but these record should be fairly short and infrequent compared to DATA records... (and if we would live the achieved rates out of the DATA records we might even save some space). We jast need the achieved rates and the timestamp when the values were read last.

**Comment by lynxthecat** [comment]
OK I've implemented these changes with the latest commits.

**Comment by moeller0** [comment]
So, this looks good. I created a PR to teach the parser to read these in (and more importantly to help over the change in the data header record type name).
