### ISSUE TITLE
missing header lines

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#64]
I just tried to test the current version and adjust the parser to read in the LOAD records as well. I got the impression that on log rotatio nthe headers are written reliably but at first start of autorate we do somehow not write these headers. Maybe we could simply force a log rotation on start so that there is only one place that needs to know about headers?

**Comment by lynxthecat** [comment]
Yes you are right! The headers were printed with log rotate but the log rotate was conditional on an existing /var/log/cake-autorate.log. Fixed with this commit: https://github.com/lynxthecat/cake-autorate/commit/d75e404628dd33acfcb1422af70b4bf0c1346a17.

**Comment by lynxthecat** [comment]
If you could test all is well then I can close.

**Comment by moeller0** [comment]
Seems to work! Thanks.

**Comment by moeller0** [comment]
Shall I close this or do you want to have the honors?

**Comment by lynxthecat** [comment]
OK I'll close. Nice fix here.
