### ISSUE TITLE
Netdata plugin

### ISSUE THREAD

**Issue by pannal** [lynxthecat/cake-autorate#69]
Hey,

I've seen the continuous development on graphing lately. Would it be possible to add a netdata plugin for this?

That'd be awesome.

Thanks

**Comment by lynxthecat** [comment]
Not sure. Since the graphic uses octave I imagine a server would need to receive data and send back .png files. So not sure this is feasible? @moeller0?

**Comment by moeller0** [comment]
I have zero experience with net data but I assume it will be quite different from the current model used by the octave code.

**Comment by pannal** [comment]
> Not sure. Since the graphic uses octave I imagine a server would need to receive data and send back .png files. So not sure this is feasible? @moeller0?

Netdata plugins work differently. You expose data via a plugin and Netdata takes care of aggregation and everything else. There's no images to generate as all of this is pretty modern via SVG graphs.

Maybe I'll try my luck with a plugin for Netdata.

**Comment by lynxthecat** [comment]
Any progress?
