### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#73]
I think the latest exploration and changes are worth a new version number. You ended up fixing a core part of the controller. Sure, for most users the change will be hard to notice, but it certainly increases the trust in robustness and reliability.

**Comment by lynxthecat** [comment]
Yes good point. I just want to sneak in the reflector stat monitoring though.

**Comment by richb-hanover** [comment]
I wonder if the tip from [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#effort) might be helpful for reducing the effort of keeping a changelog. The suggestion is to have an "unreleased" section where you note changes as you're making them. Once they're good enough to release, you only need to copy that section into the Released section... (PS Congratulations on making the software better...)

**Comment by lynxthecat** [comment]
Thanks @richb-hanover for the pointer. I will read that and follow it. Since this project I've never maintained a project before so I've been learning as I've been going along. So Iappreciate the advice.

**Comment by moeller0** [comment]
> Yes good point. I just want to sneak in the reflector stat monitoring though.

;) I think once we have the "multiple concurrent autorate instances" stuff tested, it is time for a new release, no? As helpful as being cleverer with reflector selection/replacement is going to be, that is something users can do manually already and just start with a decent set of reflectors, while starting multiple instances is really something out of scope for most users?

**Comment by lynxthecat** [comment]
Perhaps 1.2.0 is almost there now. Finally! My intention is to make tsping subject of 1.3.0 since full OWD support seems like worthy of a version change.

**Comment by moeller0** [comment]
6 more days ;)

**Comment by lynxthecat** [comment]
Indeed. Maybe we stick to the plan and just iron out any further issues on main? I'm hoping the new 'testing' is stable. Or do you think there could still be that deep sleep bug?

**Comment by moeller0** [comment]
> Indeed. Maybe we stick to the plan and just iron out any further issues on main? I'm hoping the new 'testing' is stable. Or do you think there could still be that deep sleep bug?

I think we (mostly you) did a number of justified changes that improve over all code quality and robustness, but I am not sure we fully caught the deep sleep issue. But for you this is super rare and for me it is also rare ever since my link behaved sanely again. So we might need more testers than we got in "testing" so a release seems still a good idea, even though it is going to be a 1.2.0 with all the excitement & adventure a .0 promises ;)

**Comment by lynxthecat** [comment]
I think we are now steadily approaching time to issue 2.0.0 release incorporating all the many changes from @rany2.

**Comment by lynxthecat** [comment]
Getting there. tsping seems like it might be stable now.

**Comment by richb-hanover** [comment]
Cool beans. Thanks for the update

**Comment by richb-hanover** [comment]
@lynxthecat I have been reviewing the many changes to the master branch. The inclusion of `tsping` makes it seem like a significant improvement from the 2.0.0 release from mid-April.

What's your plan for a release? Will you call it 2.1.0 (or some such name)? I think it deserves it. Thanks.

**Comment by lynxthecat** [comment]
I think this will be the long overdue 2.0.0 release since I held off and held off and held off. Any chance you could test the latest code on master?

**Comment by richb-hanover** [comment]
> I think this will be the long overdue 2.0.0 release...

Hmmm... you've already released code that claims to be 2.0.0. If you get bug reports, you won't know which "2.0.0" was in operation. Better to give it a new name/version number of 2.1.0. That'll also give you an opportunity to add a new section to the CHANGELOG that describes the considerable changes that have occurred since mid-April.

> Any chance you could test the latest code on master?

Yes, but not for a few days: I'll aim for later this week. I'll probably set my test unit (Archer C7) back to factory defaults and then follow the installation instructions rigorously. Are the steps in the README up to date? Thanks again

**Comment by lynxthecat** [comment]
No worries; we've waited so long for this release so far, some more time for some more valuable testing would be great. It's stable on my system so far, and the main Starlink user indicates that it is stable on his too (so far).

**Comment by richb-hanover** [comment]
@lynxthecat @moeller0 What's the prognosis for a release? Thanks.

**Comment by lynxthecat** [comment]
Ripe! I believe cake-autorate is stable now. I personally run the the `fping` variant 24/7. @bairhys identified a significant bug: https://github.com/lynxthecat/cake-autorate/issues/192, but that has been dealt with. @bairhys can you confirm things have been stable since that fix on the `tsping` variant? 

@richb-hanover or @moeller0 if you happened to have any time to do some testing to verify all looks well that'd be helpful., but not essential. 

I only have these outstanding questions: https://github.com/lynxthecat/cake-autorate/issues/196

**Comment by bairhys** [comment]
Hey @lynxthecat, I'm still on 1c671b0 with tsping and had no issues at all, it has been excellent.

**Comment by lynxthecat** [comment]
@bairhys could you test latest version?

**Comment by bairhys** [comment]
@lynxthecat I just updated to 9a07666 with no issues. It renamed my files ok and continued to use my old config automatically. I like the new version file.

**Comment by lynxthecat** [comment]
Excellent - we have @rany2 to thank for renaming the files and improving the installer/updater script that now includes the new version file. 

Any other issues you can see @rany2 before I go ahead and finally issue the overdue 2.0.0 release?

**Comment by rany2** [comment]
@lynxthecat I'll have a look later today, but it looks neat so far. Nice job with the IPC work, there's some changes I think I could make for some of the logic which could help with performance so if you want you might want to hold off until I'm done with that.

**Comment by lynxthecat** [comment]
Thanks - yes that was a rather extensive recoding exercise to implement the new IPC mechanism (mostly in this commit here: https://github.com/lynxthecat/cake-autorate/commit/d930b2184f36a15f02214948b73f6ed904e5a1d4). I think it took me the greater part of an entire day. I'll hold off for your suggestions for now.

**Comment by lynxthecat** [comment]
@rany2 and others can we release 2.0.0 now or any other pressing matters? I am thinking of updating the 'stable' branch with the latest commit in 'master' and then issuing a GitHub release, and making an announcement on the OpenWrt forum. 

@bairhys if you have time please can you run the latest `setup.sh` and verify the reported `version.txt` matches the latest commit, and then let us know if all works well? I think we're pretty much there now for stable release.

**Comment by moeller0** [comment]
As I said before, I would have released 2.0 loooooong ago, and would be at 2.X.y by now already.

Regarding 115 that seems like a job for collectd/luci-app-statistics, not sure whether the cake script for collectd does not already store the currently set rate...

**Comment by richb-hanover** [comment]
I'll second @moeller0's comment: cake-autorate is definitely good enough to push out as 2.0.0. 

Let's move any changes or further experimentation into a follow-up release.

**Comment by lynxthecat** [comment]
OK, I'll aim to release 2.0.0 tomorrow. 333 commits is probably enough, right 😆.

![image](https://github.com/lynxthecat/cake-autorate/assets/10721999/a1b24e8f-fd6e-4fba-911c-dadf00c97f50)

**Comment by bairhys** [comment]
I just updated again now after 3 days, looks like it updated as expected:

```bash
root@OpenWrt:~# cat cake-autorate/version.txt
version=2.0.0
commit=9a076663dce44fd3fa1e364fa21dda9a37831c29
root@OpenWrt:~# wget -O /tmp/cake-autorate_setup.sh https://raw.githubusercontent.com/lynxthecat/cake-autorate/master/setup.sh
Downloading 'https://raw.githubusercontent.com/lynxthecat/cake-autorate/master/setup.sh'
Connecting to 185.199.109.133:443
Writing to '/tmp/cake-autorate_setup.sh'
/tmp/cake-autorate_s 100% |*******************************|  5303   0:00:00 ETA
Download completed (5303 bytes)
root@OpenWrt:~# sh /tmp/cake-autorate_setup.sh
At least one instance of cake-autorate appears to be running - exiting
If you want to install a new version, first stop any running instance of cake-autorate
If you are sure that no instance of cake-autorate is running, delete the /var/run/cake-autorate directory
root@OpenWrt:~# service cake-autorate stop
root@OpenWrt:~# sh /tmp/cake-autorate_setup.sh
Installing cake-autorate in /root/cake-autorate...
Previous configuration present - keep it? [Y/n] y
Using prior configuration

2.0.0 successfully installed, but not yet running

Start the software manually with:
   cd /root/cake-autorate; ./cake-autorate.sh
Run as a service with:
   service cake-autorate enable; service cake-autorate start

root@OpenWrt:~# service cake-autorate start
root@OpenWrt:~# cat cake-autorate/version.txt
version=2.0.0
commit=7350fc06db65f75bc236a644cacefb1efd7f4bc6
root@OpenWrt:~#
```

Did the log file location change? just noticed my grafana plots stopped updating

**Comment by bairhys** [comment]
Thanks @lynxthecat, I'll investigate a bit later. I also think it's ready for a 2.0.0 release, it has been rock solid.

**Comment by lynxthecat** [comment]
Let's wait for you to verify the config file issue is all OK.

**Comment by rany2** [comment]
@lynxthecat IMO it might be worth release it as 2.1.0  just because I bet we're gonna get bug reports for 2.0.0 which actually isn't 2.0.0

**Comment by lynxthecat** [comment]
@rany @richb-hanover suggested 3.0.0. I felt like that would be skipping a version since I never truly released 2.0.0. What do you think?

**Comment by richb-hanover** [comment]
I say, go for 3.0.0. The `master` branch has been labeled 2.0.0 since 16 Feb 2023 (dff8db0) That number has been sitting out there for too long for us to spend any time defending the position, "No, no, this is _really_ version 2.0.0..."

The Earth will continue to revolve around the Sun, and no one will be surprised/upset/disoriented if the CHANGELOG said something like:

> ## 2023-07-08 - Version 3.0.0
> 
> - Version 3.0.0 of _cake-autorate_ is the culmination of dozens of experiments, iterative improvements, and testing that are described in the 2.0.0 section below. To indicate that the current code contains significant enhancements (and avoid confusion), we decided to release this code with a new version number.
> 
> ## 2023-07-05 - Version 2.0.0 
> ... all the previous 2.0 items...

**Comment by bairhys** [comment]
Hey @lynxthecat, you were right, it was

```
root@OpenWrt:~/cake-autorate# ./cake-autorate.sh
...
The value of 'dl_delay_thr_ms' in config file: '/root/cake-autorate/config.primary.sh' is not a valid value of type: 'float'.
The value of 'ul_delay_thr_ms' in config file: '/root/cake-autorate/config.primary.sh' is not a valid value of type: 'float'.
``` 

so I added a `.0` and cake-autorate and my grafana plots work again

```
...
dl_delay_thr_ms=30.0 # (milliseconds) 
ul_delay_thr_ms=30.0 # (milliseconds)
```

Thanks again

**Comment by rany2** [comment]
> @rany @richb-hanover suggested 3.0.0. I felt like that would be skipping a version since I never truly released 2.0.0. What do you think? And @moeller0? Wouldn't skipping to 3.0.0 without 2.0.0 somehow violate some sort of order of the universe. Or would releasing 2.0.0 be worse. Thoughts appreciated!

I couldn't care less so long as you aren't releasing it as 2.0.0.

**Comment by lynxthecat** [comment]
OK @richb-hanover I agree with your approach.

**Comment by lynxthecat** [comment]
@rany2 have I missed anything: https://github.com/lynxthecat/cake-autorate/commit/bb485e5569d54b191dc23b02ad19b18ad1ce84a0?

**Comment by richb-hanover** [comment]
CONGRATULATIONS! This is a huge step. A couple fussy items "around the edges":

- The master branch on the github page lists version 1.2.0. 

   <img width="219" alt="image" src="https://github.com/lynxthecat/cake-autorate/assets/1094930/1bed5c68-be61-4984-be06-ea06561f7cfd">

- What branch should people see when they come to the main [github](https://github.com/lynxthecat/cake-autorate) page? (Oh... You fixed it... It used to go to `stable`, now it goes to `master`)

I will have time to install 3.0.0 on my Archer C7 tomorrow and will report back. Thank you!

**Comment by lynxthecat** [comment]
@richb-hanover I still need to push to stable.

**Comment by rany2** [comment]
[v3.0.0](https://github.com/lynxthecat/cake-autorate/releases/tag/v3.0.0) was released.
