### ISSUE TITLE
make sure we clear stored PIDs when a process is killed.

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#92]
https://github.com/lynxthecat/cake-autorate/blob/c80809586792291e9c5b49791a89804ae415d868/cake-autorate.sh#L1476
```
	# Initiate termination of ping processes and wait until complete
	kill $maintain_pingers_pid 3>&2
	wait $maintain_pingers_pid
```

since in cleanup_and_killall() we check 
```
if ! [[ -z $maintain_pingers_pid ]]; then
```
we should add:
```
	# Initiate termination of ping processes and wait until complete
	kill $maintain_pingers_pid 3>&2
	wait $maintain_pingers_pid
	maintain_pingers_pid=
```
as if maintain_pingers is not running we should not go and kill its old PID.

**Comment by lynxthecat** [comment]
I think this has been addressed now. If not, please re-open.
