### ISSUE TITLE
get rid of trapped_INT

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#93]
https://github.com/lynxthecat/cake-autorate/blob/c80809586792291e9c5b49791a89804ae415d868/cake-autorate.sh#L660

Let's get rid of the trapped_INT games, these are pretty opaque and have odd side effects. Instead pass the SILENCE parameter explicitly from monitor_pingers() which is the only place where we would catch a kill event. I like my version where cleanup_and_killall() sends -USR1 which we trap in maintain_pingers() to differentiate the final parallel killing from the sleep related kills. This seems considerably clearer than relaying on odd rules about what signals are sent by what pathways.

**Comment by lynxthecat** [comment]
Agreed; switching over to this now and will follow up with the commit that fixes this.

**Comment by moeller0** [comment]
Looks fine, thanks.
