### ISSUE TITLE
revisiting pausing maintain_pingers() sleep/pause

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#97]
https://github.com/lynxthecat/cake-autorate/blob/c80809586792291e9c5b49791a89804ae415d868/cake-autorate.sh#L1420

Staring at this some more, might our problem somehow be related that during long sleep periods we do not stop the actual pinger process (we just pause maintain_pingers()), so our FIFOs might simply run over? I do not claim to fully understand the logic, but I have a hunch that instead of sending -USR2 twiceto toggle the pause state of maintain_pingers() we might be safer with killing and starting maintain_pingers (and thereby the actuall pinger processes as well) for good, no?

**Comment by lynxthecat** [comment]
Hmm. The USR2 should just cause looping here:

```
        # Reflector maintenance loop - verifies reflectors have not gone stale and rotates reflectors as necessary
        while (($terminate_reflector_maintenance==0))
        do
                sleep_s $reflector_health_check_interval_s
                                                                                                                                                         
                (($pause_reflector_maintenance)) && continue 
```

**Comment by moeller0** [comment]
> And we do really kill maintain_pingers() on sleep - we only pause it as part of the stall detection to temporarily block reflector rotation whilst we wait for new pings or new load (or global ping timeout).

Well, why do I see stall reports when entering sleep? As I said the logic is not fully clear to me. For my taste we reached a level of complexity where a state machine would be easier to read than nested while loops with differential `continue N` exits (but I accept that this is a matter of subjective preference and you need to lay out the code so that you are comfortable with it).

**Comment by lynxthecat** [comment]
> Well, why do I see stall reports when entering sleep?

You shouldn't I don't think - since stall detection is supposed to trigger as per comments here:

```
       # stall handling procedure
        # PIPESTATUS[0] == 142 corresponds with while loop timeout
        # i.e. no reflector responses within $stall_detection_thr * $ping_response_interval_us 
```

Sleep could follow stall detection in the event that the global reflector response timeout is reached following stall detection.

**Comment by lynxthecat** [comment]
I think I can close this now. If not, please re-open.
