### ISSUE TITLE
one more pid to clear?

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#98]
https://github.com/lynxthecat/cake-autorate/blob/63fff3a8fc398a8269dd8ec414a8dae59487a9f2/cake-autorate.sh#L1475

we should clear this as well... after we killed and waited on the PID, no?

**Comment by lynxthecat** [comment]
Yes thank you! Fixed here: https://github.com/lynxthecat/cake-autorate/commit/a209d77d4a9a832f8c9eb94d18def93cba4ba896.
